#Host guest (which will be renamed as plugin) and the game will be compiled from this file. Nue will use functions from here. 
#We may extrac the compilation option to another file since there are a lot of platforms. 

import std / [ options, os, osproc, parseopt, sequtils, strformat, strutils, sugar, tables, times ]
import buildscripts/[buildcommon, buildscripts, nimforueconfig, nimcachebuild]

let config = getNimForUEConfig()
const withDebug = true
const withPCH = true

let buildSwitches = @[

  "--outdir:./Binaries/nim/",
  "--mm:orc",
  "--backend:cpp",
  "--exceptions:cpp",
  "--warnings:off",
  "--ic:off",
  "--threads:off",
  "--path:$nim",
  # "--hints:off",
  "--hint:XDeclaredButNotUsed:off",
  "--hint:Name:off",
  "--hint:DuplicateModuleImport:off",
  "-d:useMalloc",
  "-d:withReinstantiation",
  "-d:genFilePath:" & quotes(config.genFilePath),
  "-d:pluginDir:" & quotes(config.pluginDir),

]


let targetSwitches =
  case config.targetConfiguration:
    of Debug, Development:
      var ts = @["--opt:none"]
      if withDebug:
        ts &= @["--debugger:native", "--stacktrace:on"]
      ts
    of Shipping: @["--danger"]
      

let hostPlatformSwitches =
  block:
    when defined windows:
      @[
        "--cc:vcc"
      ]
    elif defined macosx:
      
      @[
        "--cc:clang",
        "-t:-stdlib=libc++",
        "--putenv:MACOSX_DEPLOYMENT_TARGET=10.15",
        "-t:\"-x objective-c++\"",
        "-t:-fno-unsigned-char",
        "-t:-std=c++17",
        "-t:-fno-rtti",
        "-t:-fasm-blocks",
        "-t:-fvisibility-ms-compat",
        "-t:-fvisibility-inlines-hidden",
        "-t:-fno-delete-null-pointer-checks",
        "-t:-pipe",
        "-t:-fmessage-length=0",
        "-t:-Wno-macro-redefined",
        "-t:-Wno-duplicate-decl-specifier",
        "-t:-mincremental-linker-compatible",
      ] 
    else:
      @[]

#Plugin, not sure if it should belong here
let platformDir = 
  if config.targetPlatform == Mac: 
    "Mac/x86_64" 
  else: 
    $config.targetPlatform
  #I'm pretty sure there will more specific handles for the other platforms
  #/Volumes/Store/Dropbox/GameDev/UnrealProjects/NimForUEDemo/MacOs/Plugins/NimForUE/Intermediate/Build/Mac/x86_64/UnrealEditor/Development/NimForUE/PCH.NimForUE.h.gch
let pchPath = config.pluginDir / "Intermediate" / "Build" / platformDir / "UnrealEditor" / $config.targetConfiguration / "NimForUE" / "PCH.NimForUE.h.gch"

let pluginPlatformSwitches = 
        hostPlatformSwitches &
        (if withPCH: @["-t:"&escape("-include-pch " & pchPath)] else: @[])

proc compileHost*() = 
#generateFFIGenFile(config) # this is currently generated by nue g, but it should be generated by host itself here!
  doAssert(fileExists("./src/hostnimforue/ffigen.nim"), "Please run: nue g")

  let buildFlags = @[buildSwitches, targetSwitches, hostPlatformSwitches].foldl(a & " " & b.join(" "), "")
  doAssert(execCmd(&"nim cpp {buildFlags} --header:NimForUEFFI.h --threads --tlsEmulation:off --app:lib --nomain --d:host --nimcache:.nimcache/host src/hostnimforue/hostnimforue.nim") == 0)
  # copy header
  let ffiHeaderSrc = ".nimcache/host/NimForUEFFI.h"
  let ffiHeaderDest = "NimHeaders/NimForUEFFI.h"
  copyFile(ffiHeaderSrc, ffiHeaderDest)
  log("Copied " & ffiHeaderSrc & " to " & ffiHeaderDest)

  # copy lib
  let libDir = "./Binaries/nim"
  let libDirUE = libDir / "ue"
  createDir(libDirUE)

  let hostLibName = "hostnimforue"
  let baseFullLibName = getFullLibName(hostLibName)
  let fileFullSrc = libDir/baseFullLibName
  let fileFullDst = libDirUE/baseFullLibName

  try:
    copyFile(fileFullSrc, fileFullDst)
  except OSError as e:
    when defined windows: # This will fail on windows if the host dll is in use.
      quit("Error copying to " & fileFullDst & ". " & e.msg, QuitFailure)

  log("Copied " & fileFullSrc & " to " & fileFullDst)

  when defined windows:
    let weakSymbolsLib = hostLibName & ".lib"
    copyFile(libDir/weakSymbolsLib, libDirUE/weakSymbolsLib)
  elif defined macosx: #needed for dllimport in ubt mac only
    let dst = "/usr/local/lib" / baseFullLibName
    copyFile(fileFullSrc, dst)
    log("Copied " & fileFullSrc & " to " & dst)