
#AUTOGENERATED FILE. DO NOT EDIT.

import locks
import std/dynlib
import hostbase


proc testCallUFuncOn*(obj: pointer): void {.exportc, cdecl, dynlib.} =
  type
    ProcType {.inject.} = proc (obj: pointer): void {.cdecl.}
  withLock libLock:
    let fun {.inject.} = cast[ProcType](lib.symAddr("testCallUFuncOn"))
    fun(obj)

