/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  struct NimStrPayload;
struct NimStringV2;
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
typedef NIM_CHAR tyArray__eVNFTutn6un5gcq48fQLdg[65];
N_LIB_PRIVATE N_NIMCALL(NI, writeFloatToBufferSprintf__systemZformatfloat_68)(NIM_CHAR* buf, NF value);
N_LIB_PRIVATE N_NIMCALL(void, writeToBuffer__systemZformatfloat_60)(NIM_CHAR* buf, NCSTRING value);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4399)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, addCstringN__systemZformatfloat_5)(NimStringV2& result, NCSTRING buf, NI buflen);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2& s, NI newLen);
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;

#line 549 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!(framePtr__system_3905 == ((TFrame*) NIM_NIL))) goto LA3_;
{
#line 551 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = ((NI16) 0);}	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__system_3905).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	(*s).prev = framePtr__system_3905;
#line 557 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = s;
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		callDepthLimitReached__system_4399();
}	}
	LA8_: ;
}

#line 99 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = (*framePtr__system_3905).prev;}

#line 36 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
N_LIB_PRIVATE N_NIMCALL(void, writeToBuffer__systemZformatfloat_60)(NIM_CHAR* buf, NCSTRING value) {	nimfr_("writeToBuffer", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 37 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	nimln_(37, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");	NI i = ((NI) 0);
	{
#line 38 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		nimln_(38, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");		while (1) {
#line 38 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"

#line 38 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
			if (!!(((NU8)(value[i]) == (NU8)(0)))) goto LA2;

#line 39 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
			nimln_(39, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");			buf[(i)- 0] = value[i];
#line 40 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
			nimln_(40, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");			i += ((NI) 1);		} LA2: ;
	}
	popFrame();}

#line 42 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
N_LIB_PRIVATE N_NIMCALL(NI, writeFloatToBufferSprintf__systemZformatfloat_68)(NIM_CHAR* buf, NF value) {	NI result;	nimfr_("writeFloatToBufferSprintf", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");	result = (NI)0;
#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	nimln_(47, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	int T1_ = sprintf(((char*) (buf)), "%.16g", value);	NI n = ((NI) (T1_));

#line 48 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	nimln_(48, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");	NIM_BOOL hasDot = NIM_FALSE;
	{		NI i;		NI colontmp_;		i = (NI)0;		colontmp_ = (NI)0;
#line 49 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		nimln_(49, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 49 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		colontmp_ = (NI)(n - ((NI) 1));
#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
		nimln_(90, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");		NI res = ((NI) 0);
		{
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
			nimln_(91, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");			while (1) {
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
				if (!(res <= colontmp_)) goto LA4;

#line 49 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
				nimln_(49, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");				i = res;
#line 49 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
				{
#line 50 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
					nimln_(50, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");					if (!((NU8)(buf[(i)- 0]) == (NU8)(44))) goto LA7_;
{
#line 51 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
					nimln_(51, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");					buf[(i)- 0] = 46;
#line 52 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
					nimln_(52, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");					hasDot = NIM_TRUE;}				}
				goto LA5_;
				LA7_: ;
				{
#line 53 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
					nimln_(53, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");					if (!(((NU8)(buf[(i)- 0])) >= ((NU8)(97)) && ((NU8)(buf[(i)- 0])) <= ((NU8)(122)) || ((NU8)(buf[(i)- 0])) >= ((NU8)(65)) && ((NU8)(buf[(i)- 0])) <= ((NU8)(90)) || ((NU8)(buf[(i)- 0])) == ((NU8)(46)))) goto LA10_;
{
#line 54 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
					nimln_(54, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");					hasDot = NIM_TRUE;}				}
				goto LA5_;
				LA10_: ;
				LA5_: ;

#line 93 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
				nimln_(93, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");				res += ((NI) 1);			} LA4: ;
		}
	}

#line 55 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	nimln_(55, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");	{
#line 55 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		if (!!(hasDot)) goto LA14_;
{
#line 56 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		nimln_(56, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");		buf[(n)- 0] = 46;
#line 57 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		nimln_(57, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 57 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		buf[((NI)(n + ((NI) 1)))- 0] = 48;
#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		nimln_(58, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		buf[((NI)(n + ((NI) 2)))- 0] = 0;
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		nimln_(59, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		result = (NI)(n + ((NI) 2));}	}
	goto LA12_;
	LA14_: ;
	{
#line 61 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		nimln_(61, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");		result = n;	}
	LA12_: ;

#line 65 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	nimln_(65, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");	{
#line 65 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"

#line 65 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		if (!(((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(110)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(78)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(68)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(100)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(41)))) goto LA19_;
{
#line 66 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		nimln_(66, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 66 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		writeToBuffer__systemZformatfloat_60(buf, "nan");

#line 67 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		nimln_(67, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");		result = ((NI) 3);}	}
	goto LA17_;
	LA19_: ;
	{
#line 68 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		nimln_(68, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 68 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		if (!((NU8)(buf[((NI)(n - ((NI) 1)))- 0]) == (NU8)(70))) goto LA22_;
{
#line 69 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
		nimln_(69, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");		{
#line 69 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
			if (!((NU8)(buf[(((NI) 0))- 0]) == (NU8)(45))) goto LA26_;
{
#line 70 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
			nimln_(70, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 70 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
			writeToBuffer__systemZformatfloat_60(buf, "-inf");

#line 71 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
			nimln_(71, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");			result = ((NI) 4);}		}
		goto LA24_;
		LA26_: ;
		{
#line 73 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
			nimln_(73, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 73 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
			writeToBuffer__systemZformatfloat_60(buf, "inf");

#line 74 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
			nimln_(74, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");			result = ((NI) 3);		}
		LA24_: ;
}	}
	goto LA17_;
	LA22_: ;
	LA17_: ;
	popFrame();	return result;}

#line 12 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
N_LIB_PRIVATE N_NIMCALL(void, addCstringN__systemZformatfloat_5)(NimStringV2& result, NCSTRING buf, NI buflen) {	nimfr_("addCstringN", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 14 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	nimln_(14, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 14 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	NI oldLen = result.len;

#line 15 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	nimln_(15, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 15 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	NI newLen = (NI)(oldLen + buflen);

#line 16 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	nimln_(16, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");	setLengthStrV2(result, ((NI) (newLen)));
#line 17 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	nimln_(17, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 17 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	void* T1_ = memcpy(((void*) ((&result.p->data[oldLen]))), ((void*) (buf)), ((size_t) (buflen)));	popFrame();}

#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
N_LIB_PRIVATE N_NIMCALL(void, addFloatSprintf__systemZformatfloat_111)(NimStringV2& result, NF x) {	tyArray__eVNFTutn6un5gcq48fQLdg buffer;	nimfr_("addFloatSprintf", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 95 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	nimln_(95, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 95 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"

#line 95 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	NI T1_ = writeFloatToBufferSprintf__systemZformatfloat_68(buffer, x);	NI n = T1_;

#line 96 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	nimln_(96, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim");
#line 96 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\formatfloat.nim"
	addCstringN__systemZformatfloat_5(result, ((char*) ((&buffer[(((NI) 0))- 0]))), n);
	popFrame();}
