/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  struct NimStrPayload;
struct NimStringV2;
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
struct Exception;
struct RootObj;
struct TNimTypeV2;
struct tySequence__uB9b75OUPRENsBAu4AnoePA;
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct TNimTypeV2 {void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {TNimTypeV2* m_type;};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception : public RootObj {Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA : public Exception {};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw : public tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(NI, rawParseInt__pureZparseutils_250)(NimStringV2 s, NI64& b, NI start);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res);
static N_INLINE(NIM_BOOL, nimAddInt64)(NI64 a, NI64 b, NI64* res);
static N_INLINE(NIM_BOOL, nimMulInt64)(NI64 a, NI64 b, NI64* res);
static N_INLINE(NF, toBiggestFloat__system_1687)(NI64 i);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4399)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NF, abs__system_4888)(NF x);
static N_INLINE(NIM_BOOL, nimSubInt64)(NI64 a, NI64 b, NI64* res);
N_LIB_PRIVATE N_NOINLINE(void, integerOutOfRangeError__pureZparseutils_248)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_NIMCALL(NI, nimParseBiggestFloat)(NimStringV2 s, NF& number, NI start);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res);
static N_INLINE(NF, toFloat__system_1684)(NI i);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2& s, NI newLen);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2& s);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_2330)(NimStringV2& s);
extern TNimTypeV2 NTIv2__yoNlBGx0D2tRizIdhQuENw_;
static const struct {
  NI cap; NIM_CHAR data[37+1];
} TM__vI9aZNKIcImom6dDyKXW1ZA_8 = { 37 | NIM_STRLIT_FLAG, "Parsed integer outside of valid range" };
static const NimStringV2 TM__vI9aZNKIcImom6dDyKXW1ZA_9 = {37, (NimStrPayload*)&TM__vI9aZNKIcImom6dDyKXW1ZA_8};
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;

#line 52 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 46 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 46 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI r = ((NI) ((NU)((NU64)(((NU) (a))) + (NU64)(((NU) (b))))));

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{		NIM_BOOL T3_;
#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ a));		if (T3_) goto LA4_;

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ b));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 48 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA1_;
	LA5_: ;
	{
#line 50 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 64 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI r = ((NI) ((NU)((NU64)(((NU) (a))) - (NU64)(((NU) (b))))));

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{		NIM_BOOL T3_;
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ a));		if (T3_) goto LA4_;

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ (NI)((NU64) ~(b))));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 60 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA1_;
	LA5_: ;
	{
#line 62 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 53 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimAddInt64)(NI64 a, NI64 b, NI64* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 46 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 46 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI64 r = ((NI64) ((NU64)((NU64)(((NU64) (a))) + (NU64)(((NU64) (b))))));

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{		NIM_BOOL T3_;
#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (IL64(0) <= (NI64)(r ^ a));		if (T3_) goto LA4_;

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (IL64(0) <= (NI64)(r ^ b));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 48 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA1_;
	LA5_: ;
	{
#line 50 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 549 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!(framePtr__system_3905 == ((TFrame*) NIM_NIL))) goto LA3_;
{
#line 551 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = ((NI16) 0);}	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__system_3905).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	(*s).prev = framePtr__system_3905;
#line 557 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = s;
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		callDepthLimitReached__system_4399();
}	}
	LA8_: ;
}

#line 99 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = (*framePtr__system_3905).prev;}

#line 1466 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
static N_INLINE(NF, toBiggestFloat__system_1687)(NI64 i) {	NF result;	nimfr_("toBiggestFloat", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim");	result = (NF)0;
#line 1467 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
	nimln_(1467, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim");	result = ((NF) (i));	popFrame();	return result;}

#line 1557 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
static N_INLINE(NF, abs__system_4888)(NF x) {	NF result;	result = (NF)0;
#line 1566 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"

#line 1566 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
	result = fabs(x);	return result;}

#line 111 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimMulInt64)(NI64 a, NI64 b, NI64* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI64 r = ((NI64) ((NU64)((NU64)(((NU64) (a))) * (NU64)(((NU64) (b))))));

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NF T1_ = toBiggestFloat__system_1687(a);
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NF T2_ = toBiggestFloat__system_1687(b);	NF floatProd = ((NF)(T1_) * (NF)(T2_));

#line 92 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 92 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 92 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NF T3_ = toBiggestFloat__system_1687(r);	NF resAsFloat = T3_;

#line 95 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{
#line 95 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		if (!(resAsFloat == floatProd)) goto LA6_;
{
#line 96 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA4_;
	LA6_: ;
	{
#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		{
#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			NF T11_ = abs__system_4888(((NF)(resAsFloat) - (NF)(floatProd)));
#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			NF T12_ = abs__system_4888(floatProd);			if (!(((NF)(32.0) * (NF)(T11_)) <= T12_)) goto LA13_;
{
#line 106 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			(*res) = r;}		}
		goto LA9_;
		LA13_: ;
		{
#line 108 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			result = NIM_TRUE;		}
		LA9_: ;
	}
	LA4_: ;
	return result;}

#line 65 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimSubInt64)(NI64 a, NI64 b, NI64* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI64 r = ((NI64) ((NU64)((NU64)(((NU64) (a))) - (NU64)(((NU64) (b))))));

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{		NIM_BOOL T3_;
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (IL64(0) <= (NI64)(r ^ a));		if (T3_) goto LA4_;

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (IL64(0) <= (NI64)(r ^ (NI64)((NU64) ~(b))));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 60 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA1_;
	LA5_: ;
	{
#line 62 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 425 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
N_LIB_PRIVATE N_NOINLINE(void, integerOutOfRangeError__pureZparseutils_248)(void) {	tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T1_;	nimfr_("integerOutOfRangeError", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	T1_ = NIM_NIL;	T1_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) nimNewObj(sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw), NIM_ALIGNOF(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));	(*T1_).m_type = (&NTIv2__yoNlBGx0D2tRizIdhQuENw_);	(*T1_).name = "ValueError";	(*T1_).message = TM__vI9aZNKIcImom6dDyKXW1ZA_9;	(*T1_).parent = ((Exception*) NIM_NIL);
#line 426 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	nimln_(426, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	raiseExceptionEx((Exception*)T1_, "ValueError", "integerOutOfRangeError", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim", 426);	popFrame();}

#line 432 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
N_LIB_PRIVATE N_NIMCALL(NI, rawParseInt__pureZparseutils_250)(NimStringV2 s, NI64& b, NI start) {	NI result;	nimfr_("rawParseInt", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	result = (NI)0;
#line 434 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	nimln_(434, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	NI64 sign = IL64(-1);

#line 435 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	nimln_(435, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	NI i = start;

#line 436 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	nimln_(436, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	{
#line 436 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 436 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		if (!(i < s.len)) goto LA3_;
{
#line 437 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		nimln_(437, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");		{			NI TM__vI9aZNKIcImom6dDyKXW1ZA_2;
#line 437 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			if (i < 0 || i >= s.len){ raiseIndexError2(i,s.len-1); }			if (!((NU8)(s.p->data[i]) == (NU8)(43))) goto LA7_;
{
#line 437 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_2)) { raiseOverflow(); };			i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_2);}		}
		goto LA5_;
		LA7_: ;
		{			NI TM__vI9aZNKIcImom6dDyKXW1ZA_3;
#line 438 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			nimln_(438, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");			if (i < 0 || i >= s.len){ raiseIndexError2(i,s.len-1); }			if (!((NU8)(s.p->data[i]) == (NU8)(45))) goto LA10_;
{
#line 439 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			nimln_(439, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");			if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_3)) { raiseOverflow(); };			i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_3);
#line 440 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			nimln_(440, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");			sign = IL64(1);}		}
		goto LA5_;
		LA10_: ;
		LA5_: ;
}	}
	LA3_: ;

#line 441 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	nimln_(441, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	{		NIM_BOOL T14_;
#line 441 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		T14_ = (NIM_BOOL)0;
#line 441 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 441 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		T14_ = (i < s.len);		if (!(T14_)) goto LA15_;

#line 441 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		if (i < 0 || i >= s.len){ raiseIndexError2(i,s.len-1); }		T14_ = (((NU8)(s.p->data[i])) >= ((NU8)(48)) && ((NU8)(s.p->data[i])) <= ((NU8)(57)));		LA15_: ;
		if (!T14_) goto LA16_;
{
#line 442 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		nimln_(442, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");		b = IL64(0);		{
#line 443 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			nimln_(443, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");			while (1) {				NIM_BOOL T20_;				NI TM__vI9aZNKIcImom6dDyKXW1ZA_4;				NI TM__vI9aZNKIcImom6dDyKXW1ZA_10;
#line 443 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				T20_ = (NIM_BOOL)0;
#line 443 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 443 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				T20_ = (i < s.len);				if (!(T20_)) goto LA21_;

#line 443 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				if (i < 0 || i >= s.len){ raiseIndexError2(i,s.len-1); }				T20_ = (((NU8)(s.p->data[i])) >= ((NU8)(48)) && ((NU8)(s.p->data[i])) <= ((NU8)(57)));				LA21_: ;
				if (!T20_) goto LA19;

#line 444 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				nimln_(444, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");
#line 444 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 444 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				if (i < 0 || i >= s.len){ raiseIndexError2(i,s.len-1); }				if (nimSubInt(((NU8)(s.p->data[i])), ((NI) 48), &TM__vI9aZNKIcImom6dDyKXW1ZA_4)) { raiseOverflow(); };				NI c = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_4);

#line 445 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				nimln_(445, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");				{					NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_5;					NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_6;					NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_7;
#line 445 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 445 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 445 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
					if (nimAddInt64((IL64(-9223372036854775807) - IL64(1)), ((NI64) (c)), &TM__vI9aZNKIcImom6dDyKXW1ZA_5)) { raiseOverflow(); };					if (!((NI64)((NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_5) / IL64(10)) <= b)) goto LA24_;
{
#line 446 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
					nimln_(446, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");
#line 446 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 446 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
					if (nimMulInt64(b, IL64(10), &TM__vI9aZNKIcImom6dDyKXW1ZA_6)) { raiseOverflow(); };					if (nimSubInt64((NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_6), ((NI64) (c)), &TM__vI9aZNKIcImom6dDyKXW1ZA_7)) { raiseOverflow(); };					b = (NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_7);}				}
				goto LA22_;
				LA24_: ;
				{
#line 448 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
					nimln_(448, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");
#line 448 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
					integerOutOfRangeError__pureZparseutils_248();
				}
				LA22_: ;

#line 449 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				nimln_(449, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");				if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_10)) { raiseOverflow(); };				i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_10);				{
#line 450 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
					nimln_(450, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");					while (1) {						NIM_BOOL T29_;						NI TM__vI9aZNKIcImom6dDyKXW1ZA_11;
#line 450 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
						T29_ = (NIM_BOOL)0;
#line 450 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 450 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
						T29_ = (i < s.len);						if (!(T29_)) goto LA30_;

#line 450 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
						if (i < 0 || i >= s.len){ raiseIndexError2(i,s.len-1); }						T29_ = ((NU8)(s.p->data[i]) == (NU8)(95));						LA30_: ;
						if (!T29_) goto LA28;

#line 450 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
						if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_11)) { raiseOverflow(); };						i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_11);					} LA28: ;
				}
			} LA19: ;
		}

#line 451 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		nimln_(451, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");		{			NIM_BOOL T33_;
#line 451 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			T33_ = (NIM_BOOL)0;
#line 451 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			T33_ = (sign == IL64(-1));			if (!(T33_)) goto LA34_;

#line 451 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			T33_ = (b == (IL64(-9223372036854775807) - IL64(1)));			LA34_: ;
			if (!T33_) goto LA35_;
{
#line 452 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			nimln_(452, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");
#line 452 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			integerOutOfRangeError__pureZparseutils_248();
}		}
		goto LA31_;
		LA35_: ;
		{			NI64 TM__vI9aZNKIcImom6dDyKXW1ZA_12;			NI TM__vI9aZNKIcImom6dDyKXW1ZA_13;
#line 454 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			nimln_(454, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");
#line 454 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			if (nimMulInt64(b, sign, &TM__vI9aZNKIcImom6dDyKXW1ZA_12)) { raiseOverflow(); };			b = (NI64)(TM__vI9aZNKIcImom6dDyKXW1ZA_12);
#line 455 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			nimln_(455, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");
#line 455 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			if (nimSubInt(i, start, &TM__vI9aZNKIcImom6dDyKXW1ZA_13)) { raiseOverflow(); };			result = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_13);		}
		LA31_: ;
}	}
	LA16_: ;
	popFrame();	return result;}

#line 460 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
N_LIB_PRIVATE N_NIMCALL(NI, npuParseBiggestInt)(NimStringV2 s, NI64& number, NI start) {	NI result;	nimfr_("parseBiggestInt", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	result = (NI)0;
#line 469 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	nimln_(469, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	NI64 res = IL64(0);

#line 472 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	nimln_(472, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");
#line 472 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	result = rawParseInt__pureZparseutils_250(s, res, start);
#line 473 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	nimln_(473, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	{
#line 473 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 473 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		if (!!((result == ((NI) 0)))) goto LA3_;
{
#line 474 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		nimln_(474, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");		number = res;}	}
	LA3_: ;
	popFrame();	return result;}

#line 582 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
N_LIB_PRIVATE N_NIMCALL(NI, npuParseFloat)(NimStringV2 s, NF& number, NI start) {	NI result;	nimfr_("parseFloat", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	result = (NI)0;
#line 595 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	nimln_(595, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	NF bf = 0.0;

#line 596 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	nimln_(596, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");
#line 596 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 596 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	result = nimParseBiggestFloat(s, bf, start);
#line 597 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	nimln_(597, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	{
#line 597 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 597 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		if (!!((result == ((NI) 0)))) goto LA3_;
{
#line 598 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		nimln_(598, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");		number = bf;}	}
	LA3_: ;
	popFrame();	return result;}

#line 1452 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
static N_INLINE(NF, toFloat__system_1684)(NI i) {	NF result;	nimfr_("toFloat", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim");	result = (NF)0;
#line 1453 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
	nimln_(1453, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim");	result = ((NF) (i));	popFrame();	return result;}

#line 110 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI r = ((NI) ((NU)((NU64)(((NU) (a))) * (NU64)(((NU) (b))))));

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NF T1_ = toFloat__system_1684(a);
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NF T2_ = toFloat__system_1684(b);	NF floatProd = ((NF)(T1_) * (NF)(T2_));

#line 92 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 92 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 92 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NF T3_ = toFloat__system_1684(r);	NF resAsFloat = T3_;

#line 95 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{
#line 95 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		if (!(resAsFloat == floatProd)) goto LA6_;
{
#line 96 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA4_;
	LA6_: ;
	{
#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		{
#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			NF T11_ = abs__system_4888(((NF)(resAsFloat) - (NF)(floatProd)));
#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			NF T12_ = abs__system_4888(floatProd);			if (!(((NF)(32.0) * (NF)(T11_)) <= T12_)) goto LA13_;
{
#line 106 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			(*res) = r;}		}
		goto LA9_;
		LA13_: ;
		{
#line 108 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			result = NIM_TRUE;		}
		LA9_: ;
	}
	LA4_: ;
	return result;}

#line 495 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
N_LIB_PRIVATE N_NIMCALL(NI, parseSaturatedNatural__pureZparseutils_308)(NimStringV2 s, NI& b, NI start) {	NI result;	nimfr_("parseSaturatedNatural", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	result = (NI)0;
#line 505 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	nimln_(505, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	NI i = start;

#line 506 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	nimln_(506, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	{		NIM_BOOL T3_;		NI TM__vI9aZNKIcImom6dDyKXW1ZA_14;
#line 506 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		T3_ = (NIM_BOOL)0;
#line 506 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 506 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		T3_ = (i < s.len);		if (!(T3_)) goto LA4_;

#line 506 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		if (i < 0 || i >= s.len){ raiseIndexError2(i,s.len-1); }		T3_ = ((NU8)(s.p->data[i]) == (NU8)(43));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 506 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_14)) { raiseOverflow(); };		i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_14);}	}
	LA5_: ;

#line 507 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	nimln_(507, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	{		NIM_BOOL T9_;		NI TM__vI9aZNKIcImom6dDyKXW1ZA_21;
#line 507 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		T9_ = (NIM_BOOL)0;
#line 507 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 507 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		T9_ = (i < s.len);		if (!(T9_)) goto LA10_;

#line 507 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		if (i < 0 || i >= s.len){ raiseIndexError2(i,s.len-1); }		T9_ = (((NU8)(s.p->data[i])) >= ((NU8)(48)) && ((NU8)(s.p->data[i])) <= ((NU8)(57)));		LA10_: ;
		if (!T9_) goto LA11_;
{
#line 508 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		nimln_(508, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");		b = ((NI) 0);		{
#line 509 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
			nimln_(509, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");			while (1) {				NIM_BOOL T15_;				NI TM__vI9aZNKIcImom6dDyKXW1ZA_15;				NI TM__vI9aZNKIcImom6dDyKXW1ZA_19;
#line 509 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				T15_ = (NIM_BOOL)0;
#line 509 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 509 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				T15_ = (i < s.len);				if (!(T15_)) goto LA16_;

#line 509 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				if (i < 0 || i >= s.len){ raiseIndexError2(i,s.len-1); }				T15_ = (((NU8)(s.p->data[i])) >= ((NU8)(48)) && ((NU8)(s.p->data[i])) <= ((NU8)(57)));				LA16_: ;
				if (!T15_) goto LA14;

#line 510 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				nimln_(510, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");
#line 510 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 510 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				if (i < 0 || i >= s.len){ raiseIndexError2(i,s.len-1); }				if (nimSubInt(((NU8)(s.p->data[i])), ((NI) 48), &TM__vI9aZNKIcImom6dDyKXW1ZA_15)) { raiseOverflow(); };				NI c = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_15);

#line 511 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				nimln_(511, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");				{					NI TM__vI9aZNKIcImom6dDyKXW1ZA_16;					NI TM__vI9aZNKIcImom6dDyKXW1ZA_17;					NI TM__vI9aZNKIcImom6dDyKXW1ZA_18;
#line 511 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 511 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 511 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
					if (nimSubInt(((NI) IL64(9223372036854775807)), c, &TM__vI9aZNKIcImom6dDyKXW1ZA_16)) { raiseOverflow(); };					if (!(b <= (NI)((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_16) / ((NI) 10)))) goto LA19_;
{
#line 512 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
					nimln_(512, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");
#line 512 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 512 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
					if (nimMulInt(b, ((NI) 10), &TM__vI9aZNKIcImom6dDyKXW1ZA_17)) { raiseOverflow(); };					if (nimAddInt((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_17), c, &TM__vI9aZNKIcImom6dDyKXW1ZA_18)) { raiseOverflow(); };					b = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_18);}				}
				goto LA17_;
				LA19_: ;
				{
#line 514 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
					nimln_(514, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");					b = ((NI) IL64(9223372036854775807));				}
				LA17_: ;

#line 515 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				nimln_(515, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");				if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_19)) { raiseOverflow(); };				i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_19);				{
#line 516 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
					nimln_(516, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");					while (1) {						NIM_BOOL T24_;						NI TM__vI9aZNKIcImom6dDyKXW1ZA_20;
#line 516 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
						T24_ = (NIM_BOOL)0;
#line 516 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 516 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
						T24_ = (i < s.len);						if (!(T24_)) goto LA25_;

#line 516 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
						if (i < 0 || i >= s.len){ raiseIndexError2(i,s.len-1); }						T24_ = ((NU8)(s.p->data[i]) == (NU8)(95));						LA25_: ;
						if (!T24_) goto LA23;

#line 516 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
						if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_20)) { raiseOverflow(); };						i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_20);					} LA23: ;
				}
			} LA14: ;
		}

#line 517 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		nimln_(517, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");
#line 517 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
		if (nimSubInt(i, start, &TM__vI9aZNKIcImom6dDyKXW1ZA_21)) { raiseOverflow(); };		result = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_21);}	}
	LA11_: ;
	popFrame();	return result;}

#line 168 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2& s) {
#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
	{		NIM_BOOL T3_;
#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
		T3_ = (NIM_BOOL)0;
#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"

#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
		T3_ = !((s.p == ((NimStrPayload*) NIM_NIL)));		if (!(T3_)) goto LA4_;

#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"

#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
		T3_ = ((NI)((*s.p).cap & ((NI) IL64(4611686018427387904))) == ((NI) IL64(4611686018427387904)));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 170 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"

#line 170 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
		nimPrepareStrMutationImpl__system_2330(s);
}	}
	LA5_: ;
}

#line 328 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
N_LIB_PRIVATE N_NIMCALL(void, fastSubstr__pureZparseutils_170)(NimStringV2 s, NimStringV2& token, NI start, NI length) {	nimfr_("fastSubstr", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");
#line 329 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
	nimln_(329, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");	if ((length) < ((NI) 0) || (length) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(length, ((NI) 0), ((NI) IL64(9223372036854775807))); }	setLengthStrV2(token, ((NI) (length)));	{		NI i;		i = (NI)0;
#line 119 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
		nimln_(119, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");		NI i_2 = ((NI) 0);
		{
#line 120 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
			nimln_(120, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");			while (1) {				NI TM__vI9aZNKIcImom6dDyKXW1ZA_22;				NI TM__vI9aZNKIcImom6dDyKXW1ZA_23;
#line 120 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
				if (!(i_2 < length)) goto LA3;

#line 330 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				nimln_(330, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim");				i = i_2;				if (i < 0 || i >= token.len){ raiseIndexError2(i,token.len-1); }				nimPrepareStrMutationV2(token);
#line 330 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"

#line 330 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\parseutils.nim"
				if (nimAddInt(i, start, &TM__vI9aZNKIcImom6dDyKXW1ZA_22)) { raiseOverflow(); };				if ((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_22) < 0 || (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_22) >= s.len){ raiseIndexError2((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_22),s.len-1); }				token.p->data[i] = s.p->data[(NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_22)];
#line 122 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
				nimln_(122, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");				if (nimAddInt(i_2, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_23)) { raiseOverflow(); };				i_2 = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_23);			} LA3: ;
		}
	}
	popFrame();}
