/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include "UEDeps.h"
#include "nimbase.h"
    
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  struct tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ;
struct NimStrPayload;
struct NimStringV2;
struct tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw;
struct tyObject_Option__9bYx4GXowbLkybgCTrklnyw;
struct tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
struct tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A;
struct tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ {UPackage* val;
};
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw {UClass* val;
};
struct tyObject_Option__9bYx4GXowbLkybgCTrklnyw {UScriptStruct* val;
};
struct tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ {UFunction* val;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A {NI bytes;
NI16* data;
};
typedef NI16 tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag[1];


#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      
#line 20 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\definitions.nim"
#pragma warning(disable: 4101) 

static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ, someNil__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_41)(UPackage* val);
static N_INLINE(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_93)(void);
static N_INLINE(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_96)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4399)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ, some__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_115)(UPackage* val);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__systemZassertions_66)(NimStringV2 msg);
N_LIB_PRIVATE N_NIMCALL(UPackage*, getPackageByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_15)(FString packageShortName);
static N_INLINE(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw, someNil__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_215)(UClass* val);
static N_INLINE(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_267)(void);
static N_INLINE(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_270)(void);
static N_INLINE(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw, some__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_289)(UClass* val);
N_LIB_PRIVATE N_NIMCALL(UClass*, getUETypeByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_362)(UPackage* pkg, FString name);
N_LIB_PRIVATE N_NIMCALL(FString, amp___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_93)(FString a, FString b);
N_LIB_PRIVATE N_NIMCALL(FString, amp___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_101)(FString a, NimStringV2 b);
static N_INLINE(tyObject_Option__9bYx4GXowbLkybgCTrklnyw, someNil__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_488)(UScriptStruct* val);
static N_INLINE(tyObject_Option__9bYx4GXowbLkybgCTrklnyw, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_540)(void);
static N_INLINE(tyObject_Option__9bYx4GXowbLkybgCTrklnyw, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_543)(void);
static N_INLINE(tyObject_Option__9bYx4GXowbLkybgCTrklnyw, some__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_562)(UScriptStruct* val);
N_LIB_PRIVATE N_NIMCALL(UScriptStruct*, getUETypeByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_478)(UPackage* pkg, FString name);
static N_INLINE(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ, someNil__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_703)(UFunction* val);
static N_INLINE(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_787)(void);
static N_INLINE(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_790)(void);
static N_INLINE(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ, some__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_809)(UFunction* val);
N_LIB_PRIVATE N_NIMCALL(UFunction*, getUETypeByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_693)(UPackage* pkg, FString name);
N_LIB_PRIVATE N_NIMCALL(FString, getShortName__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_128)(UPackage* pkg);
static N_INLINE(FString, toFStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_78)(NimStringV2 str);
static N_INLINE(FString, f__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_33)(NimStringV2 str);
static N_INLINE(FString, makeFString__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_18)(NimStringV2 str);
static N_INLINE(NI16*, toWideCString__systemZwidestrs_41)(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A x);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A, newWideCString__systemZwidestrs_276)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___systemZwidestrs_6)(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A& a);
static N_INLINE(NimStringV2, X5BX5D___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_131)(NimStringV2* s, NI sLen_0, NI i);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_3279)(NimStringV2& dest, NimStringV2 src);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitString)(NimStringV2 s, NimStringV2 sep, NI maxsplit);
static N_INLINE(NimStringV2, toStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_75)(FString fstr);
static N_INLINE(NimStringV2, dollar___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_36)(FString fstr);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZwidestrs_343)(NI16* s);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3276)(NimStringV2& dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3769)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ& dest);
static const struct {
  NI cap; NIM_CHAR data[75+1];
} TM__hjSh9cJ0ewXqjkGL6hPFSyw_2 = { 75 | NIM_STRLIT_FLAG, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim(133, 5) `not val.isNil` " };
static const NimStringV2 TM__hjSh9cJ0ewXqjkGL6hPFSyw_3 = {75, (NimStrPayload*)&TM__hjSh9cJ0ewXqjkGL6hPFSyw_2};
static const NimStringV2 TM__hjSh9cJ0ewXqjkGL6hPFSyw_4 = {75, (NimStrPayload*)&TM__hjSh9cJ0ewXqjkGL6hPFSyw_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__hjSh9cJ0ewXqjkGL6hPFSyw_5 = { 1 | NIM_STRLIT_FLAG, "." };
static const NimStringV2 TM__hjSh9cJ0ewXqjkGL6hPFSyw_6 = {1, (NimStrPayload*)&TM__hjSh9cJ0ewXqjkGL6hPFSyw_5};
static const NimStringV2 TM__hjSh9cJ0ewXqjkGL6hPFSyw_7 = {75, (NimStrPayload*)&TM__hjSh9cJ0ewXqjkGL6hPFSyw_2};
static const NimStringV2 TM__hjSh9cJ0ewXqjkGL6hPFSyw_8 = {1, (NimStrPayload*)&TM__hjSh9cJ0ewXqjkGL6hPFSyw_5};
static const NimStringV2 TM__hjSh9cJ0ewXqjkGL6hPFSyw_9 = {75, (NimStrPayload*)&TM__hjSh9cJ0ewXqjkGL6hPFSyw_2};
static const NimStringV2 TM__hjSh9cJ0ewXqjkGL6hPFSyw_10 = {1, (NimStrPayload*)&TM__hjSh9cJ0ewXqjkGL6hPFSyw_5};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__hjSh9cJ0ewXqjkGL6hPFSyw_12 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__hjSh9cJ0ewXqjkGL6hPFSyw_13 = {0, (NimStrPayload*)&TM__hjSh9cJ0ewXqjkGL6hPFSyw_12};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__hjSh9cJ0ewXqjkGL6hPFSyw_14 = { 1 | NIM_STRLIT_FLAG, "/" };
static const NimStringV2 TM__hjSh9cJ0ewXqjkGL6hPFSyw_15 = {1, (NimStrPayload*)&TM__hjSh9cJ0ewXqjkGL6hPFSyw_14};
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;

#line 19 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
#line 21 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"

#line 21 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
	void* T1_ = memset(a, v, ((size_t) (size)));}

#line 30 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
#line 31 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"

#line 31 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}

#line 549 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!(framePtr__system_3905 == ((TFrame*) NIM_NIL))) goto LA3_;
{
#line 551 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = ((NI16) 0);}	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__system_3905).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	(*s).prev = framePtr__system_3905;
#line 557 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = s;
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		callDepthLimitReached__system_4399();
}	}
	LA8_: ;
}

#line 99 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = (*framePtr__system_3905).prev;}

#line 139 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
static N_INLINE(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_96)(void) {	tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ result;	nimfr_("none", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ));	popFrame();	return result;}

#line 152 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
static N_INLINE(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_93)(void) {	tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ result;	nimfr_("none", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ));
#line 153 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(153, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(154, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	result = none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_96();	popFrame();	return result;}

#line 119 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
static N_INLINE(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ, some__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_115)(UPackage* val) {	tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ result;	nimfr_("some", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ));
#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(133, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	{
#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		if (!!(!((val == 0)))) goto LA3_;
{
#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		failedAssertImpl__systemZassertions_66(TM__hjSh9cJ0ewXqjkGL6hPFSyw_3);
}	}
	LA3_: ;

#line 134 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(134, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	result.val = val;	popFrame();	return result;}

#line 149 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
static N_INLINE(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ, someNil__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_41)(UPackage* val) {	tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ result;	tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ colontmpD_;	tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ colontmpD__2;	nimfr_("someNil", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ));	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ));	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ));
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
	nimln_(150, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim");
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
	{
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		if (!(val == ((UPackage*) NIM_NIL))) goto LA3_;
{
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"

#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		colontmpD_ = none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_93();		result = colontmpD_;}	}
	goto LA1_;
	LA3_: ;
	{
#line 151 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		nimln_(151, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim");
#line 151 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		colontmpD__2 = some__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_115(val);		result = colontmpD__2;	}
	LA1_: ;
	popFrame();	return result;}

#line 21 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
N_LIB_PRIVATE N_NIMCALL(UPackage*, getPackageByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_15)(FString packageShortName) {	UPackage* result;	nimfr_("getPackageByName", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");	result = (UPackage*)0;
#line 22 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	nimln_(22, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");
#line 22 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	result = FindObject<UPackage>(((UObject*) NIM_NIL), *FPackageName::ConvertToLongScriptPackageName(*packageShortName));	popFrame();	return result;}

#line 24 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ, tryGetPackageByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_34)(FString packageName) {	tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ result;	nimfr_("tryGetPackageByName", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__BBNuuxOrRB1aoapKkBgXtQ));
#line 25 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	nimln_(25, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");
#line 25 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 25 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	UPackage* T1_ = getPackageByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_15(packageName);
#line 25 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	result = someNil__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_41(T1_);	popFrame();	return result;}

#line 139 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
static N_INLINE(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_270)(void) {	tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw result;	nimfr_("none", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw));	popFrame();	return result;}

#line 152 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
static N_INLINE(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_267)(void) {	tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw result;	nimfr_("none", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw));
#line 153 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(153, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(154, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	result = none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_270();	popFrame();	return result;}

#line 119 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
static N_INLINE(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw, some__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_289)(UClass* val) {	tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw result;	nimfr_("some", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw));
#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(133, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	{
#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		if (!!(!((val == 0)))) goto LA3_;
{
#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		failedAssertImpl__systemZassertions_66(TM__hjSh9cJ0ewXqjkGL6hPFSyw_4);
}	}
	LA3_: ;

#line 134 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(134, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	result.val = val;	popFrame();	return result;}

#line 149 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
static N_INLINE(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw, someNil__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_215)(UClass* val) {	tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw result;	tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw colontmpD_;	tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw colontmpD__2;	nimfr_("someNil", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw));	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw));	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw));
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
	nimln_(150, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim");
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
	{
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		if (!(val == ((UClass*) NIM_NIL))) goto LA3_;
{
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"

#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		colontmpD_ = none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_267();		result = colontmpD_;}	}
	goto LA1_;
	LA3_: ;
	{
#line 151 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		nimln_(151, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim");
#line 151 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		colontmpD__2 = some__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_289(val);		result = colontmpD__2;	}
	LA1_: ;
	popFrame();	return result;}

#line 37 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
N_LIB_PRIVATE N_NIMCALL(UClass*, getUETypeByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_362)(UPackage* pkg, FString name) {	UClass* result;	nimfr_("getUETypeByName", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");	result = (UClass*)0;
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	nimln_(38, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	FString T1_ = amp___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_101(pkg->GetName(), TM__hjSh9cJ0ewXqjkGL6hPFSyw_6);
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	FString T2_ = amp___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_93(T1_, name);	FString fullName = T2_;

#line 39 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	nimln_(39, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");	result = FindObject<UClass>(pkg, *fullName);	popFrame();	return result;}

#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw, tryGetUETypeByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_354)(UPackage* pkg, FString name) {	tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw result;	nimfr_("tryGetUETypeByName", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__o1Dz0XY4QCffOUrlI9clUhw));
#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	nimln_(42, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");
#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	UClass* T1_ = getUETypeByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_362(pkg, name);
#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	result = someNil__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_215(T1_);	popFrame();	return result;}

#line 139 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
static N_INLINE(tyObject_Option__9bYx4GXowbLkybgCTrklnyw, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_543)(void) {	tyObject_Option__9bYx4GXowbLkybgCTrklnyw result;	nimfr_("none", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__9bYx4GXowbLkybgCTrklnyw));	popFrame();	return result;}

#line 152 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
static N_INLINE(tyObject_Option__9bYx4GXowbLkybgCTrklnyw, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_540)(void) {	tyObject_Option__9bYx4GXowbLkybgCTrklnyw result;	nimfr_("none", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__9bYx4GXowbLkybgCTrklnyw));
#line 153 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(153, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(154, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	result = none__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_543();	popFrame();	return result;}

#line 119 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
static N_INLINE(tyObject_Option__9bYx4GXowbLkybgCTrklnyw, some__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_562)(UScriptStruct* val) {	tyObject_Option__9bYx4GXowbLkybgCTrklnyw result;	nimfr_("some", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__9bYx4GXowbLkybgCTrklnyw));
#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(133, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	{
#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		if (!!(!((val == 0)))) goto LA3_;
{
#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		failedAssertImpl__systemZassertions_66(TM__hjSh9cJ0ewXqjkGL6hPFSyw_7);
}	}
	LA3_: ;

#line 134 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(134, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	result.val = val;	popFrame();	return result;}

#line 149 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
static N_INLINE(tyObject_Option__9bYx4GXowbLkybgCTrklnyw, someNil__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_488)(UScriptStruct* val) {	tyObject_Option__9bYx4GXowbLkybgCTrklnyw result;	tyObject_Option__9bYx4GXowbLkybgCTrklnyw colontmpD_;	tyObject_Option__9bYx4GXowbLkybgCTrklnyw colontmpD__2;	nimfr_("someNil", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__9bYx4GXowbLkybgCTrklnyw));	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_Option__9bYx4GXowbLkybgCTrklnyw));	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_Option__9bYx4GXowbLkybgCTrklnyw));
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
	nimln_(150, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim");
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
	{
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		if (!(val == ((UScriptStruct*) NIM_NIL))) goto LA3_;
{
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"

#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		colontmpD_ = none__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_540();		result = colontmpD_;}	}
	goto LA1_;
	LA3_: ;
	{
#line 151 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		nimln_(151, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim");
#line 151 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		colontmpD__2 = some__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_562(val);		result = colontmpD__2;	}
	LA1_: ;
	popFrame();	return result;}

#line 37 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
N_LIB_PRIVATE N_NIMCALL(UScriptStruct*, getUETypeByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_478)(UPackage* pkg, FString name) {	UScriptStruct* result;	nimfr_("getUETypeByName", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");	result = (UScriptStruct*)0;
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	nimln_(38, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	FString T1_ = amp___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_101(pkg->GetName(), TM__hjSh9cJ0ewXqjkGL6hPFSyw_8);
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	FString T2_ = amp___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_93(T1_, name);	FString fullName = T2_;

#line 39 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	nimln_(39, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");	result = FindObject<UScriptStruct>(pkg, *fullName);	popFrame();	return result;}

#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_Option__9bYx4GXowbLkybgCTrklnyw, tryGetUETypeByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_470)(UPackage* pkg, FString name) {	tyObject_Option__9bYx4GXowbLkybgCTrklnyw result;	nimfr_("tryGetUETypeByName", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__9bYx4GXowbLkybgCTrklnyw));
#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	nimln_(42, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");
#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	UScriptStruct* T1_ = getUETypeByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_478(pkg, name);
#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	result = someNil__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_488(T1_);	popFrame();	return result;}

#line 139 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
static N_INLINE(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_790)(void) {	tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ result;	nimfr_("none", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ));	popFrame();	return result;}

#line 152 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
static N_INLINE(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ, none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_787)(void) {	tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ result;	nimfr_("none", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ));
#line 153 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(153, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(154, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	result = none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_790();	popFrame();	return result;}

#line 119 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
static N_INLINE(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ, some__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_809)(UFunction* val) {	tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ result;	nimfr_("some", "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ));
#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(133, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	{
#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		if (!!(!((val == 0)))) goto LA3_;
{
#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		failedAssertImpl__systemZassertions_66(TM__hjSh9cJ0ewXqjkGL6hPFSyw_9);
}	}
	LA3_: ;

#line 134 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimln_(134, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim");	result.val = val;	popFrame();	return result;}

#line 149 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
static N_INLINE(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ, someNil__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_703)(UFunction* val) {	tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ result;	tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ colontmpD_;	tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ colontmpD__2;	nimfr_("someNil", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ));	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ));	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ));
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
	nimln_(150, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim");
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
	{
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		if (!(val == ((UFunction*) NIM_NIL))) goto LA3_;
{
#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"

#line 150 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		colontmpD_ = none__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_787();		result = colontmpD_;}	}
	goto LA1_;
	LA3_: ;
	{
#line 151 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		nimln_(151, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim");
#line 151 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\utils\\utils.nim"
		colontmpD__2 = some__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_809(val);		result = colontmpD__2;	}
	LA1_: ;
	popFrame();	return result;}

#line 37 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
N_LIB_PRIVATE N_NIMCALL(UFunction*, getUETypeByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_693)(UPackage* pkg, FString name) {	UFunction* result;	nimfr_("getUETypeByName", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");	result = (UFunction*)0;
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	nimln_(38, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	FString T1_ = amp___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_101(pkg->GetName(), TM__hjSh9cJ0ewXqjkGL6hPFSyw_10);
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	FString T2_ = amp___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_93(T1_, name);	FString fullName = T2_;

#line 39 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	nimln_(39, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");	result = FindObject<UFunction>(pkg, *fullName);	popFrame();	return result;}

#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ, tryGetUETypeByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_685)(UPackage* pkg, FString name) {	tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ result;	nimfr_("tryGetUETypeByName", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Option__s9a9aseZ6uZVOtEjzRsBBpEQ));
#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	nimln_(42, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");
#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	UFunction* T1_ = getUETypeByName__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_693(pkg, name);
#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	result = someNil__OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_703(T1_);	popFrame();	return result;}

#line 53 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
static N_INLINE(NI16*, toWideCString__systemZwidestrs_41)(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A x) {	NI16* result;	nimfr_("toWideCString", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	result = (NI16*)0;
#line 54 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(54, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	result = x.data;	popFrame();	return result;}

#line 27 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
static N_INLINE(FString, makeFString__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_18)(NimStringV2 str) {	FString result;	tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A colontmpD_;	nimfr_("makeFString", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A));
#line 28 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	nimln_(28, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");
#line 29 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	nimln_(29, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");
#line 29 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"

#line 29 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"

#line 29 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	colontmpD_ = newWideCString__systemZwidestrs_276(str);
#line 29 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	NI16* T1_ = toWideCString__systemZwidestrs_41(colontmpD_);	result = FString(reinterpret_cast<TCHAR*>(T1_));
#line 28 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(28, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 28 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	eqdestroy___systemZwidestrs_6(colontmpD_);
	popFrame();	return result;}

#line 31 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
static N_INLINE(FString, f__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_33)(NimStringV2 str) {	FString result;	nimfr_("f", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");
#line 31 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	nimln_(31, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");
#line 31 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	result = makeFString__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_18(str);	popFrame();	return result;}

#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
static N_INLINE(FString, toFStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_78)(NimStringV2 str) {	FString result;	nimfr_("toFStr", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");
#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	nimln_(42, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");
#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	result = f__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_33(str);	popFrame();	return result;}

#line 64 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI r = ((NI) ((NU)((NU64)(((NU) (a))) - (NU64)(((NU) (b))))));

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{		NIM_BOOL T3_;
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ a));		if (T3_) goto LA4_;

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ (NI)((NU64) ~(b))));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 60 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA1_;
	LA5_: ;
	{
#line 62 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 2641 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
static N_INLINE(NimStringV2, X5BX5D___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_131)(NimStringV2* s, NI sLen_0, NI i) {	NimStringV2 result;	NI TM__hjSh9cJ0ewXqjkGL6hPFSyw_11;	nimfr_("[]", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim");	result.len = 0; result.p = NIM_NIL;
#line 54 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\fatal.nim"
	nimln_(54, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\fatal.nim");
#line 2642 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
	nimln_(2642, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim");
#line 2642 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
	if (nimSubInt(sLen_0, i, &TM__hjSh9cJ0ewXqjkGL6hPFSyw_11)) { raiseOverflow(); };	if ((NI)(TM__hjSh9cJ0ewXqjkGL6hPFSyw_11) < 0 || (NI)(TM__hjSh9cJ0ewXqjkGL6hPFSyw_11) >= sLen_0){ raiseIndexError2((NI)(TM__hjSh9cJ0ewXqjkGL6hPFSyw_11),sLen_0-1); }
#line 54 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\fatal.nim"
	nimln_(54, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\fatal.nim");	eqcopy___system_3279(result, s[(NI)(TM__hjSh9cJ0ewXqjkGL6hPFSyw_11)]);
	popFrame();	return result;}

#line 33 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
static N_INLINE(NimStringV2, dollar___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_36)(FString fstr) {	NimStringV2 result;	NimStringV2 T1_;	nimfr_("$", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");	result.len = 0; result.p = NIM_NIL;	T1_.len = 0; T1_.p = NIM_NIL;
#line 34 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	nimln_(34, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");	{		NI T4_;
#line 34 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"

#line 34 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"

#line 34 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
		T4_ = (NI)0;		T4_ = fstr.GetCharArray().Num();		if (!(((NI) (T4_)) == ((NI) 0))) goto LA5_;
{
#line 34 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
		result = TM__hjSh9cJ0ewXqjkGL6hPFSyw_13;}	}
	goto LA2_;
	LA5_: ;
	{		TCHAR* T8_;
#line 35 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
		nimln_(35, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");
#line 35 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"

#line 35 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
		T8_ = (TCHAR*)0;		T8_ = fstr.GetCharArray().GetData();
#line 35 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
		result = dollar___systemZwidestrs_343(((NI16*) (T8_)));	}
	LA2_: ;
	popFrame();	return result;}

#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
static N_INLINE(NimStringV2, toStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_75)(FString fstr) {	NimStringV2 result;	nimfr_("toStr", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");	result.len = 0; result.p = NIM_NIL;
#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	nimln_(41, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");
#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	result = dollar___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_36(fstr);	popFrame();	return result;}

#line 30 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
N_LIB_PRIVATE N_NIMCALL(FString, getShortName__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_128)(UPackage* pkg) {	FString result;	NimStringV2 colontmpD_;	tySequence__sM4lkSb7zS6F7OVMvW9cffQ colontmpD__2;	NimStringV2 colontmpD__3;	nimfr_("getShortName", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
#line 30 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	nimln_(30, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");
#line 30 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 30 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 30 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 30 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 30 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	colontmpD_ = toStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_75(pkg->GetName());
#line 30 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	colontmpD__2 = nsuSplitString(colontmpD_, TM__hjSh9cJ0ewXqjkGL6hPFSyw_15, ((NI) -1));
#line 30 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	colontmpD__3 = X5BX5D___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_131(((colontmpD__2).p) ? (colontmpD__2.p->data) : NIM_NIL, colontmpD__2.len, ((NI) 1));
#line 30 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	result = toFStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_78(colontmpD__3);
#line 54 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\fatal.nim"
	nimln_(54, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\fatal.nim");
#line 54 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\fatal.nim"
	eqdestroy___system_3276(colontmpD__3);

#line 2264 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
	nimln_(2264, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim");
#line 2264 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
	eqdestroy___system_3769(colontmpD__2);

#line 54 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\fatal.nim"
	nimln_(54, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\fatal.nim");
#line 54 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\fatal.nim"
	eqdestroy___system_3276(colontmpD_);
	popFrame();	return result;}

#line 34 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
N_LIB_PRIVATE N_NIMCALL(FString, getModuleName__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_153)(UObject* obj) {	FString result;	nimfr_("getModuleName", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");
#line 34 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	nimln_(34, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim");
#line 34 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"

#line 34 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\package.nim"
	result = getShortName__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZpackage_128(obj->GetPackage());	popFrame();	return result;}
