/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include "UEDeps.h"
#include "nimbase.h"
    
#include "UEGenClassDefs.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  struct FVertexInstanceID_;
struct tyObject_Params__36Am9cQwLWASo3rpztGSoqQ;
struct NimStrPayload;
struct NimStringV2;
struct tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A;
struct FPolygonGroupID_;
struct tyObject_Params__doKTrtIjvu4O9cvXCn2O9cuQ;
struct tyObject_Params__uuX4RnAhRQW9aaMgh9cTZKwg;
struct FPolygonID_;
struct tyObject_Params__VPN1WdBiPgStdJN4R59cJ1A;
struct FUVMapSettings_;
typedef NU8 tyArray__H8qf9bpC2ziYA2earmO8m7w[4];
struct FVertexInstanceID_ {tyArray__H8qf9bpC2ziYA2earmO8m7w pad_0;
};
struct tyObject_Params__36Am9cQwLWASo3rpztGSoqQ {FVertexInstanceID_ vertexInstanceID;
FVector2D uV;
NI32 uVIndex;
};
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A {NI bytes;
NI16* data;
};
typedef NI16 tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag[1];
struct FPolygonGroupID_ {tyArray__H8qf9bpC2ziYA2earmO8m7w pad_0;
};
struct tyObject_Params__doKTrtIjvu4O9cvXCn2O9cuQ {FPolygonGroupID_ polygonGroupID;
FName slotName;
};
struct tyObject_Params__uuX4RnAhRQW9aaMgh9cTZKwg {FVertexInstanceID_ vertexInstanceID;
NI32 uVIndex;
FVector2D returnValue;
};
struct FPolygonID_ {tyArray__H8qf9bpC2ziYA2earmO8m7w pad_0;
};
struct tyObject_Params__VPN1WdBiPgStdJN4R59cJ1A {FVector center;
FVector halfExtents;
FPolygonGroupID_ polygonGroup;
FPolygonID_ polygonID_PlusX;
FPolygonID_ polygonID_MinusX;
FPolygonID_ polygonID_PlusY;
FPolygonID_ polygonID_MinusY;
FPolygonID_ polygonID_PlusZ;
FPolygonID_ polygonID_MinusZ;
};
struct FUVMapSettings_ {FVector size;
FVector2D uVTile;
FVector position;
FRotator rotation;
FVector scale;
};

#line 20 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\definitions.nim"
#pragma warning(disable: 4101) 

N_LIB_PRIVATE N_NIMCALL(void, setVertexInstanceUV_)(UStaticMeshDescription_* self, FVertexInstanceID_ vertexInstanceID, FVector2D uV, NI32 uVIndex);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(FName, n__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZnametypes_15)(FString str);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4399)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(FString, toFStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_78)(NimStringV2 str);
static N_INLINE(FString, f__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_33)(NimStringV2 str);
static N_INLINE(FString, makeFString__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_18)(NimStringV2 str);
static N_INLINE(NI16*, toWideCString__systemZwidestrs_41)(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A x);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A, newWideCString__systemZwidestrs_276)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___systemZwidestrs_6)(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A& a);
N_LIB_PRIVATE N_NIMCALL(UClass*, getClassByName)(FString className);
N_LIB_PRIVATE N_NIMCALL(void, setPolygonGroupMaterialSlotName_)(UStaticMeshDescription_* self, FPolygonGroupID_ polygonGroupID, FName& slotName);
N_LIB_PRIVATE N_NIMCALL(FVector2D, getVertexInstanceUV_)(UStaticMeshDescription_* self, FVertexInstanceID_ vertexInstanceID, NI32 uVIndex);
N_LIB_PRIVATE N_NIMCALL(void, createCube_)(UStaticMeshDescription_* self, FVector center, FVector halfExtents, FPolygonGroupID_ polygonGroup, FPolygonID_& polygonID_PlusX, FPolygonID_& polygonID_MinusX, FPolygonID_& polygonID_PlusY, FPolygonID_& polygonID_MinusY, FPolygonID_& polygonID_PlusZ, FPolygonID_& polygonID_MinusZ);
N_LIB_PRIVATE N_NIMCALL(void, keepUStaticMeshDescription)(UStaticMeshDescription_* fake);
N_LIB_PRIVATE N_NIMCALL(void, keepFUVMapSettings)(FUVMapSettings_ fake);
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__35sM3jq0O9cNeb4KMnso6kA_2 = { 19 | NIM_STRLIT_FLAG, "SetVertexInstanceUV" };
static const NimStringV2 TM__35sM3jq0O9cNeb4KMnso6kA_3 = {19, (NimStrPayload*)&TM__35sM3jq0O9cNeb4KMnso6kA_2};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__35sM3jq0O9cNeb4KMnso6kA_4 = { 21 | NIM_STRLIT_FLAG, "StaticMeshDescription" };
static const NimStringV2 TM__35sM3jq0O9cNeb4KMnso6kA_5 = {21, (NimStrPayload*)&TM__35sM3jq0O9cNeb4KMnso6kA_4};
static const struct {
  NI cap; NIM_CHAR data[31+1];
} TM__35sM3jq0O9cNeb4KMnso6kA_6 = { 31 | NIM_STRLIT_FLAG, "SetPolygonGroupMaterialSlotName" };
static const NimStringV2 TM__35sM3jq0O9cNeb4KMnso6kA_7 = {31, (NimStrPayload*)&TM__35sM3jq0O9cNeb4KMnso6kA_6};
static const NimStringV2 TM__35sM3jq0O9cNeb4KMnso6kA_8 = {21, (NimStrPayload*)&TM__35sM3jq0O9cNeb4KMnso6kA_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__35sM3jq0O9cNeb4KMnso6kA_9 = { 19 | NIM_STRLIT_FLAG, "GetVertexInstanceUV" };
static const NimStringV2 TM__35sM3jq0O9cNeb4KMnso6kA_10 = {19, (NimStrPayload*)&TM__35sM3jq0O9cNeb4KMnso6kA_9};
static const NimStringV2 TM__35sM3jq0O9cNeb4KMnso6kA_11 = {21, (NimStrPayload*)&TM__35sM3jq0O9cNeb4KMnso6kA_4};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__35sM3jq0O9cNeb4KMnso6kA_12 = { 10 | NIM_STRLIT_FLAG, "CreateCube" };
static const NimStringV2 TM__35sM3jq0O9cNeb4KMnso6kA_13 = {10, (NimStrPayload*)&TM__35sM3jq0O9cNeb4KMnso6kA_12};
static const NimStringV2 TM__35sM3jq0O9cNeb4KMnso6kA_14 = {21, (NimStrPayload*)&TM__35sM3jq0O9cNeb4KMnso6kA_4};
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;

#line 19 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
#line 21 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"

#line 21 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
	void* T1_ = memset(a, v, ((size_t) (size)));}

#line 30 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
#line 31 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"

#line 31 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}

#line 549 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!(framePtr__system_3905 == ((TFrame*) NIM_NIL))) goto LA3_;
{
#line 551 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = ((NI16) 0);}	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__system_3905).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	(*s).prev = framePtr__system_3905;
#line 557 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = s;
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		callDepthLimitReached__system_4399();
}	}
	LA8_: ;
}

#line 99 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = (*framePtr__system_3905).prev;}

#line 18 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\nametypes.nim"
static N_INLINE(FName, n__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZnametypes_15)(FString str) {	FName result;	nimfr_("n", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\nametypes.nim");
#line 18 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\nametypes.nim"
	nimln_(18, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\coreuobject\\nametypes.nim");	result = FName(str) ;	popFrame();	return result;}

#line 53 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
static N_INLINE(NI16*, toWideCString__systemZwidestrs_41)(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A x) {	NI16* result;	nimfr_("toWideCString", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	result = (NI16*)0;
#line 54 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(54, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	result = x.data;	popFrame();	return result;}

#line 27 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
static N_INLINE(FString, makeFString__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_18)(NimStringV2 str) {	FString result;	tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A colontmpD_;	nimfr_("makeFString", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A));
#line 28 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	nimln_(28, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");
#line 29 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	nimln_(29, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");
#line 29 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"

#line 29 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"

#line 29 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	colontmpD_ = newWideCString__systemZwidestrs_276(str);
#line 29 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	NI16* T1_ = toWideCString__systemZwidestrs_41(colontmpD_);	result = FString(reinterpret_cast<TCHAR*>(T1_));
#line 28 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(28, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 28 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	eqdestroy___systemZwidestrs_6(colontmpD_);
	popFrame();	return result;}

#line 31 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
static N_INLINE(FString, f__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_33)(NimStringV2 str) {	FString result;	nimfr_("f", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");
#line 31 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	nimln_(31, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");
#line 31 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	result = makeFString__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_18(str);	popFrame();	return result;}

#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
static N_INLINE(FString, toFStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_78)(NimStringV2 str) {	FString result;	nimfr_("toFStr", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");
#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	nimln_(42, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim");
#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\unrealstring.nim"
	result = f__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_33(str);	popFrame();	return result;}

#line 13 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
N_LIB_PRIVATE N_NIMCALL(void, setVertexInstanceUV_)(UStaticMeshDescription_* self, FVertexInstanceID_ vertexInstanceID, FVector2D uV, NI32 uVIndex) {	tyObject_Params__36Am9cQwLWASo3rpztGSoqQ T1_;	nimfr_("setVertexInstanceUV", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");
#line 24 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(24, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	nimZeroMem((void*)(&T1_), sizeof(tyObject_Params__36Am9cQwLWASo3rpztGSoqQ));	T1_.vertexInstanceID = vertexInstanceID;	T1_.uV = uV;	T1_.uVIndex = uVIndex;	tyObject_Params__36Am9cQwLWASo3rpztGSoqQ param = T1_;

#line 26 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(26, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");
#line 26 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 26 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 26 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	FString T2_ = toFStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_78(TM__35sM3jq0O9cNeb4KMnso6kA_3);
#line 26 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	FName T3_ = n__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZnametypes_15(T2_);	FName fnName = T3_;

#line 27 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(27, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");
#line 27 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 27 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 27 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 27 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	FString T4_ = toFStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_78(TM__35sM3jq0O9cNeb4KMnso6kA_5);
#line 27 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	UClass* T5_ = getClassByName(T4_);	UFunction* fn = T5_->FindFunctionByName(fnName);

#line 29 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(29, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	self->ProcessEvent(fn, ((void*) ((&param))));
	popFrame();}

#line 31 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
N_LIB_PRIVATE N_NIMCALL(void, setPolygonGroupMaterialSlotName_)(UStaticMeshDescription_* self, FPolygonGroupID_ polygonGroupID, FName& slotName) {	tyObject_Params__doKTrtIjvu4O9cvXCn2O9cuQ T1_;	nimfr_("setPolygonGroupMaterialSlotName", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");
#line 39 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(39, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	nimZeroMem((void*)(&T1_), sizeof(tyObject_Params__doKTrtIjvu4O9cvXCn2O9cuQ));	T1_.polygonGroupID = polygonGroupID;	T1_.slotName = slotName;	tyObject_Params__doKTrtIjvu4O9cvXCn2O9cuQ param = T1_;

#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(41, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");
#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	FString T2_ = toFStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_78(TM__35sM3jq0O9cNeb4KMnso6kA_7);
#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	FName T3_ = n__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZnametypes_15(T2_);	FName fnName = T3_;

#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(42, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");
#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	FString T4_ = toFStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_78(TM__35sM3jq0O9cNeb4KMnso6kA_8);
#line 42 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	UClass* T5_ = getClassByName(T4_);	UFunction* fn = T5_->FindFunctionByName(fnName);

#line 44 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(44, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	self->ProcessEvent(fn, ((void*) ((&param))));

#line 45 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(45, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	slotName = param.slotName;	popFrame();}

#line 47 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
N_LIB_PRIVATE N_NIMCALL(FVector2D, getVertexInstanceUV_)(UStaticMeshDescription_* self, FVertexInstanceID_ vertexInstanceID, NI32 uVIndex) {	FVector2D result;	tyObject_Params__uuX4RnAhRQW9aaMgh9cTZKwg T1_;	nimfr_("getVertexInstanceUV", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");{
#line 57 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(57, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	nimZeroMem((void*)(&T1_), sizeof(tyObject_Params__uuX4RnAhRQW9aaMgh9cTZKwg));	T1_.vertexInstanceID = vertexInstanceID;	T1_.uVIndex = uVIndex;	tyObject_Params__uuX4RnAhRQW9aaMgh9cTZKwg param = T1_;

#line 59 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(59, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");
#line 59 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 59 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 59 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	FString T2_ = toFStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_78(TM__35sM3jq0O9cNeb4KMnso6kA_10);
#line 59 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	FName T3_ = n__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZnametypes_15(T2_);	FName fnName = T3_;

#line 60 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(60, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");
#line 60 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 60 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 60 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 60 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	FString T4_ = toFStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_78(TM__35sM3jq0O9cNeb4KMnso6kA_11);
#line 60 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	UClass* T5_ = getClassByName(T4_);	UFunction* fn = T5_->FindFunctionByName(fnName);

#line 62 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(62, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	self->ProcessEvent(fn, ((void*) ((&param))));

#line 63 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(63, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");
#line 63 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	result = param.returnValue;	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 65 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
N_LIB_PRIVATE N_NIMCALL(void, createCube_)(UStaticMeshDescription_* self, FVector center, FVector halfExtents, FPolygonGroupID_ polygonGroup, FPolygonID_& polygonID_PlusX, FPolygonID_& polygonID_MinusX, FPolygonID_& polygonID_PlusY, FPolygonID_& polygonID_MinusY, FPolygonID_& polygonID_PlusZ, FPolygonID_& polygonID_MinusZ) {	tyObject_Params__VPN1WdBiPgStdJN4R59cJ1A T1_;	nimfr_("createCube", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");
#line 87 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(87, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	nimZeroMem((void*)(&T1_), sizeof(tyObject_Params__VPN1WdBiPgStdJN4R59cJ1A));	T1_.center = center;	T1_.halfExtents = halfExtents;	T1_.polygonGroup = polygonGroup;	T1_.polygonID_PlusX = polygonID_PlusX;	T1_.polygonID_MinusX = polygonID_MinusX;	T1_.polygonID_PlusY = polygonID_PlusY;	T1_.polygonID_MinusY = polygonID_MinusY;	T1_.polygonID_PlusZ = polygonID_PlusZ;	T1_.polygonID_MinusZ = polygonID_MinusZ;	tyObject_Params__VPN1WdBiPgStdJN4R59cJ1A param = T1_;

#line 95 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(95, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");
#line 95 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 95 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 95 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	FString T2_ = toFStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_78(TM__35sM3jq0O9cNeb4KMnso6kA_13);
#line 95 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	FName T3_ = n__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZnametypes_15(T2_);	FName fnName = T3_;

#line 96 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(96, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");
#line 96 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 96 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 96 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"

#line 96 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	FString T4_ = toFStr__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZ67oreZ67ontainersZunrealstring_78(TM__35sM3jq0O9cNeb4KMnso6kA_14);
#line 96 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	UClass* T5_ = getClassByName(T4_);	UFunction* fn = T5_->FindFunctionByName(fnName);

#line 98 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(98, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	self->ProcessEvent(fn, ((void*) ((&param))));

#line 99 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(99, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	polygonID_PlusX = param.polygonID_PlusX;
#line 100 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(100, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	polygonID_MinusX = param.polygonID_MinusX;
#line 101 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(101, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	polygonID_PlusY = param.polygonID_PlusY;
#line 102 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(102, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	polygonID_MinusY = param.polygonID_MinusY;
#line 103 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(103, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	polygonID_PlusZ = param.polygonID_PlusZ;
#line 104 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
	nimln_(104, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	polygonID_MinusZ = param.polygonID_MinusZ;	popFrame();}

#line 106 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
N_LIB_PRIVATE N_NIMCALL(void, keepUStaticMeshDescription)(UStaticMeshDescription_* fake) {	nimfr_("keepUStaticMeshDescription", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	popFrame();}

#line 110 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim"
N_LIB_PRIVATE N_NIMCALL(void, keepFUVMapSettings)(FUVMapSettings_ fake) {	nimfr_("keepFUVMapSettings", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\bindings\\exported\\staticmeshdescription.nim");	popFrame();}
