/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <math.h>
#include <string.h>
#include "UEDeps.h"
#include "nimbase.h"
    
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  struct tyObject_Option__JJ9byBwkaLFkY1rQVmjxIQw;
struct NimStrPayload;
struct NimStringV2;
struct tyTuple__UV3llMMYFckfui8YMBuUZA;
struct tyObject_Option__Jf2MclyYCa3LGOUysuzbXw;
struct tyObject_NimForUEConfig__rlNt5NPcjTrcbe9cCKc0MLQ;
struct tyObject_Option__vK1KzfYf1DGLiUIpLm9cS0A;
struct TNimTypeV2;
struct tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ;
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA;
struct Exception;
struct RootObj;
struct tySequence__uB9b75OUPRENsBAu4AnoePA;
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ;
struct tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ;
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
struct tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ;
struct tyTuple__0F3Kz25HWtRatQmCDVHWEA;
struct tyObject_Option__Ir49cZUKRA6i2N0BhpFkv9aw;
struct tyObject_CtorInfo__wFO9cn4URjd9b4A2M0BBfJ4g;
struct tyObject_Option__Re9aqo9abYRdutS9bTn8F9bPuw;
struct tyObject_UEType__9cYW3S1aHjgb9aVn8pfdpTPw;
struct tySequence__KOAWoP40Kf3QIDzOGwEbgQ;
struct tySequence__KOAWoP40Kf3QIDzOGwEbgQ_Content;
struct tySequence__cul9cMq0iOFymYopcsY6o8A;
struct tySequence__cul9cMq0iOFymYopcsY6o8A_Content;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
struct tySequence__hLAAGJBCnNkBiIz3UyIu1Q;
struct tySequence__hLAAGJBCnNkBiIz3UyIu1Q_Content;
struct tyObject_Option__qo8R2yQ5weGaHkISwDID3Q;
struct tyObject_EmitterInfo__BrZyvYyxlHE3rMzRNFx0AA;
struct tyObject_Option__MNVkPw9aQD1pwm4xewFbebA;
struct tyObject_Option__ULWzrEUiwEc9bqOOzN5MYBQ;
struct tyObject_UEField__8ELKvZAJaVvp9bj9bHDDxsJQ;
struct tyObject_Option__6F1h9acoSfSNngcU9bMYFAoA;
struct tyObject_UEImportRule__hB10F9a2R59a1K2aGsI4OAFg;
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct tyObject_UEMetadata__Pp6Z0Qu19bzuGmN4riZRg6w;
struct tyObject_CppFunction__beciLkAP1mysDIzQbqLkKg;
struct tySequence__KwttHQQUxH9aTedPaQO3pwA;
struct tySequence__KwttHQQUxH9aTedPaQO3pwA_Content;
struct tyObject_CppParam__UkNWD6Ho1lewN9cXmzGclSA;
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
NimStringV2 Field0;
NimStringV2 Field1;
};
struct tyObject_Option__JJ9byBwkaLFkY1rQVmjxIQw {tyTuple__UV3llMMYFckfui8YMBuUZA val;
NIM_BOOL has;
};
typedef NU8 tyEnum_TargetConfiguration__0xrEmhXnKrhhCHaBf9aPGxw;
typedef NU8 tyEnum_TargetPlatform__cEOBU2YKteNhjQkzYWU0nw;
struct tyObject_NimForUEConfig__rlNt5NPcjTrcbe9cCKc0MLQ {NimStringV2 engineDir;
NimStringV2 gameDir;
tyEnum_TargetConfiguration__0xrEmhXnKrhhCHaBf9aPGxw targetConfiguration;
tyEnum_TargetPlatform__cEOBU2YKteNhjQkzYWU0nw targetPlatform;
NIM_BOOL withEditor;
};
struct tyObject_Option__Jf2MclyYCa3LGOUysuzbXw {tyObject_NimForUEConfig__rlNt5NPcjTrcbe9cCKc0MLQ val;
NIM_BOOL has;
};
struct tyObject_Option__vK1KzfYf1DGLiUIpLm9cS0A {NimStringV2 val;
NIM_BOOL has;
};
struct TNimTypeV2 {void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {NI rc;
NI rootIdx;
};
struct RootObj {TNimTypeV2* m_type;};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception : public RootObj {Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA : public Exception {};
struct tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ : public tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA {};
struct tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ {NI len;
NI cap;
tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ {NI len;
NI cap;
tyTuple__0F3Kz25HWtRatQmCDVHWEA* d;
};
struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ {tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ traceStack;
tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ toFree;
NI freed;
NI touched;
NI edges;
NI rcSum;
NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
void** Field0;
TNimTypeV2* Field1;
};
typedef tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyUncheckedArray__72XmdLy0QAaMtx66AmNKfA[1];
typedef N_CDECL_PTR(void, tyProc__nV3KzNdCVv9cceioLWdV9anQ) (FObjectInitializer& objectInitializer);
struct tyObject_CtorInfo__wFO9cn4URjd9b4A2M0BBfJ4g {tyProc__nV3KzNdCVv9cceioLWdV9anQ fn;
NimStringV2 hash;
NimStringV2 className;
};
struct tyObject_Option__Ir49cZUKRA6i2N0BhpFkv9aw {tyObject_CtorInfo__wFO9cn4URjd9b4A2M0BBfJ4g val;
NIM_BOOL has;
};
struct tySequence__KOAWoP40Kf3QIDzOGwEbgQ {
  NI len; tySequence__KOAWoP40Kf3QIDzOGwEbgQ_Content* p;
};
struct tySequence__cul9cMq0iOFymYopcsY6o8A {
  NI len; tySequence__cul9cMq0iOFymYopcsY6o8A_Content* p;
};
typedef NU8 tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tySequence__hLAAGJBCnNkBiIz3UyIu1Q {
  NI len; tySequence__hLAAGJBCnNkBiIz3UyIu1Q_Content* p;
};
typedef NU8 tyEnum_UEDelegateKind__F0wY5U1NjfOBWfLSMmw30Q;
struct tyObject_UEType__9cYW3S1aHjgb9aVn8pfdpTPw {NimStringV2 name;
tySequence__KOAWoP40Kf3QIDzOGwEbgQ fields;
tySequence__cul9cMq0iOFymYopcsY6o8A metadata;
tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ kind;
union{
struct {NimStringV2 parent;
NU32 clsFlags;
NimStringV2 ctorSourceHash;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ interfaces;
tySequence__hLAAGJBCnNkBiIz3UyIu1Q fnOverrides;
} _kind_1;
struct {NimStringV2 superStruct;
NU32 structFlags;
NI32 size;
NI32 alignment;
} _kind_2;
struct {tyEnum_UEDelegateKind__F0wY5U1NjfOBWfLSMmw30Q delKind;
NimStringV2 outerClassName;
} _kind_4;
};
};
struct tyObject_Option__Re9aqo9abYRdutS9bTn8F9bPuw {tyObject_UEType__9cYW3S1aHjgb9aVn8pfdpTPw val;
NIM_BOOL has;
};
typedef struct {
N_NIMCALL_PTR(UField*, ClP_0) (UPackage* i0, void* ClE_0);
void* ClE_0;
} tyProc__0GohsglovxqW8ubgyjQCMg;
struct tyObject_EmitterInfo__BrZyvYyxlHE3rMzRNFx0AA {UField* uStructPointer;
tyObject_UEType__9cYW3S1aHjgb9aVn8pfdpTPw ueType;
tyProc__0GohsglovxqW8ubgyjQCMg generator;
};
struct tyObject_Option__qo8R2yQ5weGaHkISwDID3Q {tyObject_EmitterInfo__BrZyvYyxlHE3rMzRNFx0AA val;
NIM_BOOL has;
};
struct tyObject_Option__MNVkPw9aQD1pwm4xewFbebA {tyObject_Option__Re9aqo9abYRdutS9bTn8F9bPuw val;
NIM_BOOL has;
};
typedef NU8 tyEnum_UEFieldKind__SCPYJiLruoPBUvJoApOIJg;
struct tyObject_UEField__8ELKvZAJaVvp9bj9bHDDxsJQ {NimStringV2 name;
tySequence__cul9cMq0iOFymYopcsY6o8A metadata;
tyEnum_UEFieldKind__SCPYJiLruoPBUvJoApOIJg kind;
union{
struct {NimStringV2 uePropType;
NU64 propFlags;
NI32 size;
NI32 offset;
NimStringV2 defaultParamValue;
} _kind_1;
struct {NimStringV2 className;
NimStringV2 actualFunctionName;
tySequence__KOAWoP40Kf3QIDzOGwEbgQ signature;
NU32 fnFlags;
NimStringV2 sourceHash;
} _kind_2;
};
};
struct tyObject_Option__ULWzrEUiwEc9bqOOzN5MYBQ {tyObject_UEField__8ELKvZAJaVvp9bj9bHDDxsJQ val;
NIM_BOOL has;
};
typedef NU8 tyEnum_UERuleTarget__f2zu85vuvRJUHAMd4GETHw;
typedef NU8 tyEnum_UERule__M67EE7iEAUe6YkBhBgwNAg;
struct tyObject_UEImportRule__hB10F9a2R59a1K2aGsI4OAFg {tySequence__sM4lkSb7zS6F7OVMvW9cffQ affectedTypes;
tyEnum_UERuleTarget__f2zu85vuvRJUHAMd4GETHw target;
tyEnum_UERule__M67EE7iEAUe6YkBhBgwNAg rule;
union{
struct {NimStringV2 moduleName;
} _rule_1;
struct {tySequence__sM4lkSb7zS6F7OVMvW9cffQ onlyFor;
} _rule_2;
};
};
struct tyObject_Option__6F1h9acoSfSNngcU9bMYFAoA {tyObject_UEImportRule__hB10F9a2R59a1K2aGsI4OAFg val;
NIM_BOOL has;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (FString input, tyObject_Option__Re9aqo9abYRdutS9bTn8F9bPuw* Result, void* ClE_0);
void* ClE_0;
} tyProc__5CnJNRmHPAn1kLF9a61ARkQ;
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__KOAWoP40Kf3QIDzOGwEbgQ_Content_PP
#define tySequence__KOAWoP40Kf3QIDzOGwEbgQ_Content_PP
struct tySequence__KOAWoP40Kf3QIDzOGwEbgQ_Content { NI cap; tyObject_UEField__8ELKvZAJaVvp9bj9bHDDxsJQ data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_UEMetadata__Pp6Z0Qu19bzuGmN4riZRg6w {NimStringV2 name;
NimStringV2 value;
};


#ifndef tySequence__cul9cMq0iOFymYopcsY6o8A_Content_PP
#define tySequence__cul9cMq0iOFymYopcsY6o8A_Content_PP
struct tySequence__cul9cMq0iOFymYopcsY6o8A_Content { NI cap; tyObject_UEMetadata__Pp6Z0Qu19bzuGmN4riZRg6w data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      typedef NU8 tyEnum_CppAccesSpecifier__7lbkBr9ahjYoFC1Tz9b1nb9aw;
struct tySequence__KwttHQQUxH9aTedPaQO3pwA {
  NI len; tySequence__KwttHQQUxH9aTedPaQO3pwA_Content* p;
};
struct tyObject_CppFunction__beciLkAP1mysDIzQbqLkKg {NimStringV2 name;
NimStringV2 returnType;
tyEnum_CppAccesSpecifier__7lbkBr9ahjYoFC1Tz9b1nb9aw accessSpecifier;
tySequence__KwttHQQUxH9aTedPaQO3pwA params;
};


#ifndef tySequence__hLAAGJBCnNkBiIz3UyIu1Q_Content_PP
#define tySequence__hLAAGJBCnNkBiIz3UyIu1Q_Content_PP
struct tySequence__hLAAGJBCnNkBiIz3UyIu1Q_Content { NI cap; tyObject_CppFunction__beciLkAP1mysDIzQbqLkKg data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__KOAWoP40Kf3QIDzOGwEbgQ_Content_PP
#define tySequence__KOAWoP40Kf3QIDzOGwEbgQ_Content_PP
struct tySequence__KOAWoP40Kf3QIDzOGwEbgQ_Content { NI cap; tyObject_UEField__8ELKvZAJaVvp9bj9bHDDxsJQ data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__cul9cMq0iOFymYopcsY6o8A_Content_PP
#define tySequence__cul9cMq0iOFymYopcsY6o8A_Content_PP
struct tySequence__cul9cMq0iOFymYopcsY6o8A_Content { NI cap; tyObject_UEMetadata__Pp6Z0Qu19bzuGmN4riZRg6w data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__hLAAGJBCnNkBiIz3UyIu1Q_Content_PP
#define tySequence__hLAAGJBCnNkBiIz3UyIu1Q_Content_PP
struct tySequence__hLAAGJBCnNkBiIz3UyIu1Q_Content { NI cap; tyObject_CppFunction__beciLkAP1mysDIzQbqLkKg data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__cul9cMq0iOFymYopcsY6o8A_Content_PP
#define tySequence__cul9cMq0iOFymYopcsY6o8A_Content_PP
struct tySequence__cul9cMq0iOFymYopcsY6o8A_Content { NI cap; tyObject_UEMetadata__Pp6Z0Qu19bzuGmN4riZRg6w data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__KOAWoP40Kf3QIDzOGwEbgQ_Content_PP
#define tySequence__KOAWoP40Kf3QIDzOGwEbgQ_Content_PP
struct tySequence__KOAWoP40Kf3QIDzOGwEbgQ_Content { NI cap; tyObject_UEField__8ELKvZAJaVvp9bj9bHDDxsJQ data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_CppParam__UkNWD6Ho1lewN9cXmzGclSA {NimStringV2 name;
NimStringV2 typ;
};


#ifndef tySequence__KwttHQQUxH9aTedPaQO3pwA_Content_PP
#define tySequence__KwttHQQUxH9aTedPaQO3pwA_Content_PP
struct tySequence__KwttHQQUxH9aTedPaQO3pwA_Content { NI cap; tyObject_CppParam__UkNWD6Ho1lewN9cXmzGclSA data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3276)(NimStringV2& dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_3425)(tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ& dest);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4399)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_3177)(NIM_BOOL isDestroyAction, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* s, TNimTypeV2* desc);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3314)(tySequence__uB9b75OUPRENsBAu4AnoePA& dest);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZtimes_3434)(tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ& dest, void* env);
static N_INLINE(void, nimTraceRefDyn)(void* q, void* env);
static N_INLINE(void, add__system_2736)(tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ& s, void** c, TNimTypeV2* t);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res);
static N_INLINE(NF, toFloat__system_1684)(NI i);
static N_INLINE(NF, abs__system_4888)(NF x);
N_LIB_PRIVATE N_NOCONV(void*, allocImpl__system_1725)(NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_3323)(tySequence__uB9b75OUPRENsBAu4AnoePA& dest, void* env);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_480)(tySequence__KOAWoP40Kf3QIDzOGwEbgQ& dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_265)(tySequence__cul9cMq0iOFymYopcsY6o8A& dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3769)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ& dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_1127)(tySequence__hLAAGJBCnNkBiIz3UyIu1Q& dest);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_3279)(NimStringV2& dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_483)(tySequence__KOAWoP40Kf3QIDzOGwEbgQ& dest, tySequence__KOAWoP40Kf3QIDzOGwEbgQ src);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_268)(tySequence__cul9cMq0iOFymYopcsY6o8A& dest, tySequence__cul9cMq0iOFymYopcsY6o8A src);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_3772)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ& dest, tySequence__sM4lkSb7zS6F7OVMvW9cffQ src);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_1130)(tySequence__hLAAGJBCnNkBiIz3UyIu1Q& dest, tySequence__hLAAGJBCnNkBiIz3UyIu1Q src);
N_LIB_PRIVATE TNimTypeV2 NTIv2__bq5YFIFutDsA2ou9cpZuWAQ_;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZbuildscriptsZnimforueconfig_141)(tyObject_Option__JJ9byBwkaLFkY1rQVmjxIQw& dest) {
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3276(dest.val.Field0);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3276(dest.val.Field1);
}

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZbuildscriptsZnimforueconfig_371)(tyObject_Option__Jf2MclyYCa3LGOUysuzbXw& dest) {
#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3276(dest.val.engineDir);

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3276(dest.val.gameDir);
}

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_2304)(tyObject_Option__vK1KzfYf1DGLiUIpLm9cS0A& dest) {
#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3276(dest.val);
}

#line 549 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!(framePtr__system_3905 == ((TFrame*) NIM_NIL))) goto LA3_;
{
#line 551 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = ((NI16) 0);}	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__system_3905).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	(*s).prev = framePtr__system_3905;
#line 557 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = s;
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		callDepthLimitReached__system_4399();
}	}
	LA8_: ;
}

#line 99 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = (*framePtr__system_3905).prev;}

#line 413 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\arithmetics.nim"
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {	NI result;	nimfr_("-%", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\arithmetics.nim");	result = (NI)0;
#line 414 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\arithmetics.nim"
	nimln_(414, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\arithmetics.nim");
#line 418 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\arithmetics.nim"
	nimln_(418, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\arithmetics.nim");	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));	popFrame();	return result;}

#line 64 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI r = ((NI) ((NU)((NU64)(((NU) (a))) - (NU64)(((NU) (b))))));

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{		NIM_BOOL T3_;
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ a));		if (T3_) goto LA4_;

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ (NI)((NU64) ~(b))));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 60 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA1_;
	LA5_: ;
	{
#line 62 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 474 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p) {	NIM_BOOL result;	nimfr_("nimDecRefIsLastCyclicDyn", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim");	result = (NIM_BOOL)0;
#line 475 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
	nimln_(475, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim");	{
#line 475 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"

#line 475 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
		if (!!((p == NIM_NIL))) goto LA3_;
{
#line 476 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
		nimln_(476, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim");
#line 63 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\arc.nim"
		nimln_(63, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\arc.nim");
#line 63 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\arc.nim"
		NI T5_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), ((NI) 16));		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));

#line 477 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
		nimln_(477, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim");		{
#line 477 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"

#line 477 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
			if (!((NI)((*cell).rc & ((NI) -16)) == ((NI) 0))) goto LA8_;
{
#line 478 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
			nimln_(478, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim");			result = NIM_TRUE;}		}
		goto LA6_;
		LA8_: ;
		{			NI TM__4DNs4bMUkswhWc4o4dM9bbg_2;
#line 481 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
			nimln_(481, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim");			if (nimSubInt((*cell).rc, ((NI) 16), &TM__4DNs4bMUkswhWc4o4dM9bbg_2)) { raiseOverflow(); };			(*cell).rc = (NI)(TM__4DNs4bMUkswhWc4o4dM9bbg_2);		}
		LA6_: ;

#line 483 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
		nimln_(483, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim");
#line 483 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
		rememberCycle__system_3177(result, cell, (*((TNimTypeV2**) (p))));
}	}
	LA3_: ;
	popFrame();	return result;}

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_3425)(tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ& dest) {
#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	{
#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		NIM_BOOL T3_ = nimDecRefIsLastCyclicDyn(dest.parent);		if (!T3_) goto LA4_;
{
#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		nimDestroyAndDispose(dest.parent);
}	}
	LA4_: ;

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3276(dest.message);

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3314(dest.trace);

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	{
#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		NIM_BOOL T8_ = nimDecRefIsLastCyclicDyn(dest.up);		if (!T8_) goto LA9_;
{
#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		nimDestroyAndDispose(dest.up);
}	}
	LA9_: ;
}

#line 1452 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
static N_INLINE(NF, toFloat__system_1684)(NI i) {	NF result;	nimfr_("toFloat", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim");	result = (NF)0;
#line 1453 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
	nimln_(1453, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim");	result = ((NF) (i));	popFrame();	return result;}

#line 1557 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
static N_INLINE(NF, abs__system_4888)(NF x) {	NF result;	result = (NF)0;
#line 1566 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"

#line 1566 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
	result = fabs(x);	return result;}

#line 110 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI r = ((NI) ((NU)((NU64)(((NU) (a))) * (NU64)(((NU) (b))))));

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NF T1_ = toFloat__system_1684(a);
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NF T2_ = toFloat__system_1684(b);	NF floatProd = ((NF)(T1_) * (NF)(T2_));

#line 92 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 92 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 92 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NF T3_ = toFloat__system_1684(r);	NF resAsFloat = T3_;

#line 95 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{
#line 95 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		if (!(resAsFloat == floatProd)) goto LA6_;
{
#line 96 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA4_;
	LA6_: ;
	{
#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		{
#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			NF T11_ = abs__system_4888(((NF)(resAsFloat) - (NF)(floatProd)));
#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			NF T12_ = abs__system_4888(floatProd);			if (!(((NF)(32.0) * (NF)(T11_)) <= T12_)) goto LA13_;
{
#line 106 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			(*res) = r;}		}
		goto LA9_;
		LA13_: ;
		{
#line 108 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			result = NIM_TRUE;		}
		LA9_: ;
	}
	LA4_: ;
	return result;}

#line 8 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
#line 10 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"

#line 10 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
	void* T1_ = memcpy(dest, source, ((size_t) (size)));}

#line 2234 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size) {
#line 2235 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"

#line 2235 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
	nimCopyMem(dest, source, size);
}

#line 52 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 46 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 46 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI r = ((NI) ((NU)((NU64)(((NU) (a))) + (NU64)(((NU) (b))))));

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{		NIM_BOOL T3_;
#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ a));		if (T3_) goto LA4_;

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ b));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 48 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA1_;
	LA5_: ;
	{
#line 50 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 19 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
static N_INLINE(void, add__system_2736)(tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ& s, void** c, TNimTypeV2* t) {	NI TM__4DNs4bMUkswhWc4o4dM9bbg_6;	nimfr_("add", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim");
#line 20 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
	nimln_(20, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim");	{		NI TM__4DNs4bMUkswhWc4o4dM9bbg_3;		NI TM__4DNs4bMUkswhWc4o4dM9bbg_4;		NI TM__4DNs4bMUkswhWc4o4dM9bbg_5;
#line 20 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
		if (!(s.cap <= s.len)) goto LA3_;
{
#line 21 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
		nimln_(21, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim");
#line 21 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"

#line 21 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
		if (nimMulInt(s.cap, ((NI) 3), &TM__4DNs4bMUkswhWc4o4dM9bbg_3)) { raiseOverflow(); };		s.cap = (NI)((NI)(TM__4DNs4bMUkswhWc4o4dM9bbg_3) / ((NI) 2));
#line 25 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
		nimln_(25, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim");
#line 25 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"

#line 25 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
		if (nimMulInt(s.cap, ((NI) 16), &TM__4DNs4bMUkswhWc4o4dM9bbg_4)) { raiseOverflow(); };		if (((NI)(TM__4DNs4bMUkswhWc4o4dM9bbg_4)) < ((NI) 0) || ((NI)(TM__4DNs4bMUkswhWc4o4dM9bbg_4)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__4DNs4bMUkswhWc4o4dM9bbg_4), ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 25 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
		void* T5_ = allocImpl__system_1725(((NI) ((NI)(TM__4DNs4bMUkswhWc4o4dM9bbg_4))));		tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d = ((tyTuple__N4J9cV4JZGem3ljqqj5rT0Q*) (T5_));

#line 26 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
		nimln_(26, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim");
#line 26 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
		if (nimMulInt(s.len, ((NI) 16), &TM__4DNs4bMUkswhWc4o4dM9bbg_5)) { raiseOverflow(); };		if (((NI)(TM__4DNs4bMUkswhWc4o4dM9bbg_5)) < ((NI) 0) || ((NI)(TM__4DNs4bMUkswhWc4o4dM9bbg_5)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__4DNs4bMUkswhWc4o4dM9bbg_5), ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 26 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
		copyMem__system_1709(((void*) (d)), ((void*) (s.d)), ((NI) ((NI)(TM__4DNs4bMUkswhWc4o4dM9bbg_5))));

#line 30 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
		nimln_(30, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim");
#line 30 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
		dealloc(((void*) (s.d)));

#line 31 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
		nimln_(31, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim");		s.d = d;}	}
	LA3_: ;

#line 33 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
	nimln_(33, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim");	void** colontmp_ = c;

#line 33 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
	TNimTypeV2* colontmp__2 = t;

#line 33 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
	s.d[s.len].Field0 = colontmp_;	s.d[s.len].Field1 = colontmp__2;
#line 34 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim"
	nimln_(34, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\cellseqs_v2.nim");	if (nimAddInt(s.len, ((NI) 1), &TM__4DNs4bMUkswhWc4o4dM9bbg_6)) { raiseOverflow(); };	s.len = (NI)(TM__4DNs4bMUkswhWc4o4dM9bbg_6);	popFrame();}

#line 129 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
static N_INLINE(void, nimTraceRefDyn)(void* q, void* env) {	nimfr_("nimTraceRefDyn", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim");
#line 130 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
	nimln_(130, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim");	void** p = ((void**) (q));

#line 131 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
	nimln_(131, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim");	{
#line 131 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"

#line 131 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
		if (!!(((*p) == NIM_NIL))) goto LA3_;
{
#line 132 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
		nimln_(132, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim");		tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ* j = ((tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ*) (env));

#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
		nimln_(133, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim");
#line 133 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\orc.nim"
		add__system_2736((*j).traceStack, p, (*((TNimTypeV2**) ((*p)))));
}	}
	LA3_: ;
	popFrame();}

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZtimes_3434)(tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ& dest, void* env) {
#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimTraceRefDyn(&dest.parent, env);

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqtrace___system_3323(dest.trace, env);

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimTraceRefDyn(&dest.up, env);
}

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZueemit_631)(tyObject_Option__Ir49cZUKRA6i2N0BhpFkv9aw& dest) {
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3276(dest.val.hash);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3276(dest.val.className);
}

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_3056)(tyObject_Option__Re9aqo9abYRdutS9bTn8F9bPuw& dest) {
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3276(dest.val.name);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_480(dest.val.fields);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_265(dest.val.metadata);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	switch (dest.val.kind) {
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 0):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val._kind_1.parent);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val._kind_1.ctorSourceHash);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3769(dest.val._kind_1.interfaces);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_1127(dest.val._kind_1.fnOverrides);
	}
	break;
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 1):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val._kind_2.superStruct);
	}
	break;
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 3):
	{	}
	break;
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 2):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val._kind_4.outerClassName);
	}
	break;
	default: __assume(0);
	}
}

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZemitter_917)(tyObject_Option__qo8R2yQ5weGaHkISwDID3Q& dest) {
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3276(dest.val.ueType.name);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_480(dest.val.ueType.fields);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_265(dest.val.ueType.metadata);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	switch (dest.val.ueType.kind) {
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 0):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val.ueType._kind_1.parent);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val.ueType._kind_1.ctorSourceHash);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3769(dest.val.ueType._kind_1.interfaces);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_1127(dest.val.ueType._kind_1.fnOverrides);
	}
	break;
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 1):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val.ueType._kind_2.superStruct);
	}
	break;
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 3):
	{	}
	break;
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 2):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val.ueType._kind_4.outerClassName);
	}
	break;
	default: __assume(0);
	}

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		NIM_BOOL T7_ = nimDecRefIsLastCyclicDyn(dest.val.generator.ClE_0);		if (!T7_) goto LA8_;
{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		nimDestroyAndDispose(dest.val.generator.ClE_0);
}	}
	LA8_: ;
}

#line 19 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
#line 21 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"

#line 21 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
	void* T1_ = memset(a, v, ((size_t) (size)));}

#line 30 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
#line 31 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"

#line 31 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_3059)(tyObject_Option__Re9aqo9abYRdutS9bTn8F9bPuw& dest, tyObject_Option__Re9aqo9abYRdutS9bTn8F9bPuw* src) {	tyObject_UEType__9cYW3S1aHjgb9aVn8pfdpTPw colontmp_;{
#line 34 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\comparisons.nim"
	{
#line 34 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\comparisons.nim"
		if (!((&dest.val) == (&(*src).val))) goto LA3_;
{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		goto BeforeRet_;
}	}
	LA3_: ;
	nimZeroMem((void*)(&colontmp_), sizeof(tyObject_UEType__9cYW3S1aHjgb9aVn8pfdpTPw));
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	colontmp_ = dest.val;
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimZeroMem((void*)(&dest.val), sizeof(tyObject_UEType__9cYW3S1aHjgb9aVn8pfdpTPw));
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqcopy___system_3279(dest.val.name, (*src).val.name);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqcopy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_483(dest.val.fields, (*src).val.fields);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqcopy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_268(dest.val.metadata, (*src).val.metadata);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	dest.val.kind = (*src).val.kind;
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	switch (dest.val.kind) {
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 0):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqcopy___system_3279(dest.val._kind_1.parent, (*src).val._kind_1.parent);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		dest.val._kind_1.clsFlags = (*src).val._kind_1.clsFlags;
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqcopy___system_3279(dest.val._kind_1.ctorSourceHash, (*src).val._kind_1.ctorSourceHash);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqcopy___system_3772(dest.val._kind_1.interfaces, (*src).val._kind_1.interfaces);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqcopy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_1130(dest.val._kind_1.fnOverrides, (*src).val._kind_1.fnOverrides);
	}
	break;
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 1):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqcopy___system_3279(dest.val._kind_2.superStruct, (*src).val._kind_2.superStruct);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		dest.val._kind_2.structFlags = (*src).val._kind_2.structFlags;
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		dest.val._kind_2.size = (*src).val._kind_2.size;
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		dest.val._kind_2.alignment = (*src).val._kind_2.alignment;	}
	break;
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 3):
	{	}
	break;
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 2):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		dest.val._kind_4.delKind = (*src).val._kind_4.delKind;
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqcopy___system_3279(dest.val._kind_4.outerClassName, (*src).val._kind_4.outerClassName);
	}
	break;
	default: __assume(0);
	}

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3276(colontmp_.name);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_480(colontmp_.fields);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_265(colontmp_.metadata);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	switch (colontmp_.kind) {
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 0):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(colontmp_._kind_1.parent);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(colontmp_._kind_1.ctorSourceHash);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3769(colontmp_._kind_1.interfaces);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_1127(colontmp_._kind_1.fnOverrides);
	}
	break;
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 1):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(colontmp_._kind_2.superStruct);
	}
	break;
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 3):
	{	}
	break;
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 2):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(colontmp_._kind_4.outerClassName);
	}
	break;
	default: __assume(0);
	}

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	dest.has = (*src).has;	}BeforeRet_: ;
}

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_4854)(tyObject_Option__MNVkPw9aQD1pwm4xewFbebA& dest) {
#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3276(dest.val.val.name);

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_480(dest.val.val.fields);

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_265(dest.val.val.metadata);

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	switch (dest.val.val.kind) {
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 0):
	{
#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val.val._kind_1.parent);

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val.val._kind_1.ctorSourceHash);

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3769(dest.val.val._kind_1.interfaces);

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_1127(dest.val.val._kind_1.fnOverrides);
	}
	break;
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 1):
	{
#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val.val._kind_2.superStruct);
	}
	break;
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 3):
	{	}
	break;
	case ((tyEnum_UETypeKind__9abzcQBxpqY3tqFwKNv4xjQ) 2):
	{
#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 266 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val.val._kind_4.outerClassName);
	}
	break;
	default: __assume(0);
	}
}

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_2621)(tyObject_Option__ULWzrEUiwEc9bqOOzN5MYBQ& dest) {
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3276(dest.val.name);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_265(dest.val.metadata);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	switch (dest.val.kind) {
	case ((tyEnum_UEFieldKind__SCPYJiLruoPBUvJoApOIJg) 0):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val._kind_1.uePropType);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val._kind_1.defaultParamValue);
	}
	break;
	case ((tyEnum_UEFieldKind__SCPYJiLruoPBUvJoApOIJg) 1):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val._kind_2.className);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val._kind_2.actualFunctionName);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_480(dest.val._kind_2.signature);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val._kind_2.sourceHash);
	}
	break;
	case ((tyEnum_UEFieldKind__SCPYJiLruoPBUvJoApOIJg) 2):
	{	}
	break;
	default: __assume(0);
	}
}

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_2624)(tyObject_Option__ULWzrEUiwEc9bqOOzN5MYBQ& dest, tyObject_Option__ULWzrEUiwEc9bqOOzN5MYBQ* src) {	tyObject_UEField__8ELKvZAJaVvp9bj9bHDDxsJQ colontmp_;{
#line 34 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\comparisons.nim"
	{
#line 34 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\comparisons.nim"
		if (!((&dest.val) == (&(*src).val))) goto LA3_;
{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		goto BeforeRet_;
}	}
	LA3_: ;
	nimZeroMem((void*)(&colontmp_), sizeof(tyObject_UEField__8ELKvZAJaVvp9bj9bHDDxsJQ));
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	colontmp_ = dest.val;
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	nimZeroMem((void*)(&dest.val), sizeof(tyObject_UEField__8ELKvZAJaVvp9bj9bHDDxsJQ));
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqcopy___system_3279(dest.val.name, (*src).val.name);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqcopy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_268(dest.val.metadata, (*src).val.metadata);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	dest.val.kind = (*src).val.kind;
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	switch (dest.val.kind) {
	case ((tyEnum_UEFieldKind__SCPYJiLruoPBUvJoApOIJg) 0):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqcopy___system_3279(dest.val._kind_1.uePropType, (*src).val._kind_1.uePropType);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		dest.val._kind_1.propFlags = (*src).val._kind_1.propFlags;
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		dest.val._kind_1.size = (*src).val._kind_1.size;
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		dest.val._kind_1.offset = (*src).val._kind_1.offset;
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqcopy___system_3279(dest.val._kind_1.defaultParamValue, (*src).val._kind_1.defaultParamValue);
	}
	break;
	case ((tyEnum_UEFieldKind__SCPYJiLruoPBUvJoApOIJg) 1):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqcopy___system_3279(dest.val._kind_2.className, (*src).val._kind_2.className);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqcopy___system_3279(dest.val._kind_2.actualFunctionName, (*src).val._kind_2.actualFunctionName);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqcopy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_483(dest.val._kind_2.signature, (*src).val._kind_2.signature);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		dest.val._kind_2.fnFlags = (*src).val._kind_2.fnFlags;
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqcopy___system_3279(dest.val._kind_2.sourceHash, (*src).val._kind_2.sourceHash);
	}
	break;
	case ((tyEnum_UEFieldKind__SCPYJiLruoPBUvJoApOIJg) 2):
	{	}
	break;
	default: __assume(0);
	}

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3276(colontmp_.name);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_265(colontmp_.metadata);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	switch (colontmp_.kind) {
	case ((tyEnum_UEFieldKind__SCPYJiLruoPBUvJoApOIJg) 0):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(colontmp_._kind_1.uePropType);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(colontmp_._kind_1.defaultParamValue);
	}
	break;
	case ((tyEnum_UEFieldKind__SCPYJiLruoPBUvJoApOIJg) 1):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(colontmp_._kind_2.className);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(colontmp_._kind_2.actualFunctionName);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodels_480(colontmp_._kind_2.signature);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(colontmp_._kind_2.sourceHash);
	}
	break;
	case ((tyEnum_UEFieldKind__SCPYJiLruoPBUvJoApOIJg) 2):
	{	}
	break;
	default: __assume(0);
	}

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	dest.has = (*src).has;	}BeforeRet_: ;
}

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZmodulerules_415)(tyObject_Option__6F1h9acoSfSNngcU9bMYFAoA& dest) {
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	eqdestroy___system_3769(dest.val.affectedTypes);

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	switch (dest.val.rule) {
	case ((tyEnum_UERule__M67EE7iEAUe6YkBhBgwNAg) 5):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3276(dest.val._rule_1.moduleName);
	}
	break;
	case ((tyEnum_UERule__M67EE7iEAUe6YkBhBgwNAg) 6):
	{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		eqdestroy___system_3769(dest.val._rule_2.onlyFor);
	}
	break;
	default:
	{	}
	break;
	}
}

#line 248 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZcodegenZuemeta_4884)(tyProc__5CnJNRmHPAn1kLF9a61ARkQ& dest) {
#line 248 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
	{
#line 248 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 248 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 248 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		NIM_BOOL T3_ = nimDecRefIsLastCyclicDyn(dest.ClE_0);		if (!T3_) goto LA4_;
{
#line 248 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 248 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"

#line 248 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\options.nim"
		nimDestroyAndDispose(dest.ClE_0);
}	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsNimSourcesatsNimatslibatspureatsoptionsdotnim_DatInit000)(void) {

#line 999999 "generated_not_to_break_here"
NTIv2__bq5YFIFutDsA2ou9cpZuWAQ_.destructor = (void*)eqdestroy___pureZtimes_3425; NTIv2__bq5YFIFutDsA2ou9cpZuWAQ_.size = sizeof(tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ); NTIv2__bq5YFIFutDsA2ou9cpZuWAQ_.align = NIM_ALIGNOF(tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ); NTIv2__bq5YFIFutDsA2ou9cpZuWAQ_.name = "|stdlib.options.UnpackDefect|Defect|Exception|RootObj|";
; NTIv2__bq5YFIFutDsA2ou9cpZuWAQ_.traceImpl = (void*)eqtrace___pureZtimes_3434; NTIv2__bq5YFIFutDsA2ou9cpZuWAQ_.flags = 0;}

