/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  struct tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A;
struct NimStrPayload;
struct NimStringV2;
struct tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A {NI bytes;
NI16* data;
};
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
typedef NI16 tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag[1];
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A, newWideCString__systemZwidestrs_251)(NCSTRING source, NI L);
N_LIB_PRIVATE N_NIMCALL(void, createWide__systemZwidestrs_30)(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A& a, NI bytes);
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__system_1727)(NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4399)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res);
static N_INLINE(NF, toFloat__system_1684)(NI i);
static N_INLINE(NF, abs__system_4888)(NF x);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p);
static N_INLINE(NI, nimCStrLen)(NCSTRING a);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZwidestrs_279)(NI16* w, NI estimate, NI replacement);
N_NIMCALL(NimStringV2, rawNewString)(NI cap);
N_LIB_PRIVATE N_NIMCALL(NI, ord__systemZwidestrs_44)(NI16 arg);
static N_INLINE(void, nimAddCharV1)(NimStringV2& s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2& s, NI addlen);
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;

#line 19 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
#line 21 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"

#line 21 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
	void* T1_ = memset(a, v, ((size_t) (size)));}

#line 30 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
#line 31 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"

#line 31 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}

#line 549 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!(framePtr__system_3905 == ((TFrame*) NIM_NIL))) goto LA3_;
{
#line 551 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = ((NI16) 0);}	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__system_3905).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	(*s).prev = framePtr__system_3905;
#line 557 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = s;
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		callDepthLimitReached__system_4399();
}	}
	LA8_: ;
}

#line 99 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = (*framePtr__system_3905).prev;}

#line 41 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
N_LIB_PRIVATE N_NIMCALL(void, createWide__systemZwidestrs_30)(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A& a, NI bytes) {	nimfr_("createWide", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 42 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(42, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	a.bytes = bytes;
#line 46 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(46, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 46 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	if ((bytes) < ((NI) 0) || (bytes) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(bytes, ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 46 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	void* T1_ = alloc0Impl__system_1727(((NI) (bytes)));	a.data = ((NI16*) (T1_));	popFrame();}

#line 1452 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
static N_INLINE(NF, toFloat__system_1684)(NI i) {	NF result;	nimfr_("toFloat", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim");	result = (NF)0;
#line 1453 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
	nimln_(1453, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim");	result = ((NF) (i));	popFrame();	return result;}

#line 1557 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
static N_INLINE(NF, abs__system_4888)(NF x) {	NF result;	result = (NF)0;
#line 1566 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"

#line 1566 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
	result = fabs(x);	return result;}

#line 110 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI r = ((NI) ((NU)((NU64)(((NU) (a))) * (NU64)(((NU) (b))))));

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NF T1_ = toFloat__system_1684(a);
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NF T2_ = toFloat__system_1684(b);	NF floatProd = ((NF)(T1_) * (NF)(T2_));

#line 92 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 92 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 92 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NF T3_ = toFloat__system_1684(r);	NF resAsFloat = T3_;

#line 95 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{
#line 95 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		if (!(resAsFloat == floatProd)) goto LA6_;
{
#line 96 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA4_;
	LA6_: ;
	{
#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		{
#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			NF T11_ = abs__system_4888(((NF)(resAsFloat) - (NF)(floatProd)));
#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			NF T12_ = abs__system_4888(floatProd);			if (!(((NF)(32.0) * (NF)(T11_)) <= T12_)) goto LA13_;
{
#line 106 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			(*res) = r;}		}
		goto LA9_;
		LA13_: ;
		{
#line 108 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
			result = NIM_TRUE;		}
		LA9_: ;
	}
	LA4_: ;
	return result;}

#line 52 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 46 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 46 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI r = ((NI) ((NU)((NU64)(((NU) (a))) + (NU64)(((NU) (b))))));

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{		NIM_BOOL T3_;
#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ a));		if (T3_) goto LA4_;

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ b));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 48 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA1_;
	LA5_: ;
	{
#line 50 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 64 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI r = ((NI) ((NU)((NU64)(((NU) (a))) - (NU64)(((NU) (b))))));

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{		NIM_BOOL T3_;
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ a));		if (T3_) goto LA4_;

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ (NI)((NU64) ~(b))));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 60 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA1_;
	LA5_: ;
	{
#line 62 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 148 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A, newWideCString__systemZwidestrs_251)(NCSTRING source, NI L) {	tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A result;	NI TM__R8z9bzATizpQoD67YeHNTdg_2;	NI TM__R8z9bzATizpQoD67YeHNTdg_3;	nimfr_("newWideCString", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A));
#line 149 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(149, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 149 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 149 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	if (nimMulInt(L, ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_2)) { raiseOverflow(); };	if (nimAddInt((NI)(TM__R8z9bzATizpQoD67YeHNTdg_2), ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_3)) { raiseOverflow(); };
#line 149 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	createWide__systemZwidestrs_30(result, (NI)(TM__R8z9bzATizpQoD67YeHNTdg_3));

#line 150 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(150, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	NI d = ((NI) 0);
	{		NI ch;		NI result_2;		ch = (NI)0;
#line 139 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
		nimln_(139, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");		NI i = ((NI) 0);
		result_2 = (NI)0;		{
#line 141 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
			nimln_(141, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");			while (1) {				NI TM__R8z9bzATizpQoD67YeHNTdg_25;
#line 141 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				if (!(i < L)) goto LA3;

#line 142 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(142, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");				{					NI TM__R8z9bzATizpQoD67YeHNTdg_4;
#line 98 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(98, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 98 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					if (!(((NU8)(source[i])) <= ((NI) 127))) goto LA6_;
{
#line 99 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(99, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 99 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					result_2 = ((NU8)(source[i]));
#line 100 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(100, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");					if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_4)) { raiseOverflow(); };					i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_4);}				}
				goto LA4_;
				LA6_: ;
				{
#line 101 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(101, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 101 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 101 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					if (!((NI)((NI64)(((NU8)(source[i]))) >> (NU64)(((NI) 5))) == ((NI) 6))) goto LA9_;
{
#line 103 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(103, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");					{						NI TM__R8z9bzATizpQoD67YeHNTdg_5;						NI TM__R8z9bzATizpQoD67YeHNTdg_6;						NI TM__R8z9bzATizpQoD67YeHNTdg_7;
#line 103 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 103 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						if (nimSubInt(L, ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_5)) { raiseOverflow(); };						if (!(i <= (NI)(TM__R8z9bzATizpQoD67YeHNTdg_5))) goto LA13_;
{
#line 104 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(104, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 104 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 104 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 104 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 104 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 104 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 104 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 104 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_6)) { raiseOverflow(); };						result_2 = (NI)((NI)((NU64)((NI)(((NU8)(source[i])) & ((NI) 31))) << (NU64)(((NI) 6))) | (NI)(((NU8)(source[(NI)(TM__R8z9bzATizpQoD67YeHNTdg_6)])) & ((NI) 63)));
#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(105, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");						if (nimAddInt(i, ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_7)) { raiseOverflow(); };						i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_7);}					}
					goto LA11_;
					LA13_: ;
					{						NI TM__R8z9bzATizpQoD67YeHNTdg_8;
#line 107 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(107, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");						result_2 = ((NI) 65533);
#line 108 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(108, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");						if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_8)) { raiseOverflow(); };						i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_8);					}
					LA11_: ;
}				}
				goto LA4_;
				LA9_: ;
				{
#line 109 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(109, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 109 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 109 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					if (!((NI)((NI64)(((NU8)(source[i]))) >> (NU64)(((NI) 4))) == ((NI) 14))) goto LA17_;
{
#line 110 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(110, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");					{						NI TM__R8z9bzATizpQoD67YeHNTdg_9;						NI TM__R8z9bzATizpQoD67YeHNTdg_10;						NI TM__R8z9bzATizpQoD67YeHNTdg_11;						NI TM__R8z9bzATizpQoD67YeHNTdg_12;
#line 110 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 110 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						if (nimSubInt(L, ((NI) 3), &TM__R8z9bzATizpQoD67YeHNTdg_9)) { raiseOverflow(); };						if (!(i <= (NI)(TM__R8z9bzATizpQoD67YeHNTdg_9))) goto LA21_;
{
#line 114 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(114, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 114 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 113 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(113, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 113 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 113 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 113 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 114 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(114, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 114 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 114 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 114 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_10)) { raiseOverflow(); };
#line 115 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(115, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 115 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 115 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						if (nimAddInt(i, ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_11)) { raiseOverflow(); };						result_2 = (NI)((NI)((NI)((NU64)((NI)(((NU8)(source[i])) & ((NI) 15))) << (NU64)(((NI) 12))) | (NI)((NU64)((NI)(((NU8)(source[(NI)(TM__R8z9bzATizpQoD67YeHNTdg_10)])) & ((NI) 63))) << (NU64)(((NI) 6)))) | (NI)(((NU8)(source[(NI)(TM__R8z9bzATizpQoD67YeHNTdg_11)])) & ((NI) 63)));
#line 116 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(116, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");						if (nimAddInt(i, ((NI) 3), &TM__R8z9bzATizpQoD67YeHNTdg_12)) { raiseOverflow(); };						i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_12);}					}
					goto LA19_;
					LA21_: ;
					{						NI TM__R8z9bzATizpQoD67YeHNTdg_13;
#line 118 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(118, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");						result_2 = ((NI) 65533);
#line 119 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(119, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");						if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_13)) { raiseOverflow(); };						i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_13);					}
					LA19_: ;
}				}
				goto LA4_;
				LA17_: ;
				{
#line 120 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(120, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 120 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 120 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					if (!((NI)((NI64)(((NU8)(source[i]))) >> (NU64)(((NI) 3))) == ((NI) 30))) goto LA25_;
{
#line 121 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(121, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");					{						NI TM__R8z9bzATizpQoD67YeHNTdg_14;						NI TM__R8z9bzATizpQoD67YeHNTdg_15;						NI TM__R8z9bzATizpQoD67YeHNTdg_16;						NI TM__R8z9bzATizpQoD67YeHNTdg_17;						NI TM__R8z9bzATizpQoD67YeHNTdg_18;
#line 121 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 121 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						if (nimSubInt(L, ((NI) 4), &TM__R8z9bzATizpQoD67YeHNTdg_14)) { raiseOverflow(); };						if (!(i <= (NI)(TM__R8z9bzATizpQoD67YeHNTdg_14))) goto LA29_;
{
#line 127 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(127, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 127 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 126 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(126, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 125 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(125, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 125 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 125 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 125 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 126 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(126, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 126 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 126 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 126 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_15)) { raiseOverflow(); };
#line 127 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(127, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 127 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 127 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 127 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						if (nimAddInt(i, ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_16)) { raiseOverflow(); };
#line 128 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(128, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 128 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 128 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						if (nimAddInt(i, ((NI) 3), &TM__R8z9bzATizpQoD67YeHNTdg_17)) { raiseOverflow(); };						result_2 = (NI)((NI)((NI)((NI)((NU64)((NI)(((NU8)(source[i])) & ((NI) 7))) << (NU64)(((NI) 18))) | (NI)((NU64)((NI)(((NU8)(source[(NI)(TM__R8z9bzATizpQoD67YeHNTdg_15)])) & ((NI) 63))) << (NU64)(((NI) 12)))) | (NI)((NU64)((NI)(((NU8)(source[(NI)(TM__R8z9bzATizpQoD67YeHNTdg_16)])) & ((NI) 63))) << (NU64)(((NI) 6)))) | (NI)(((NU8)(source[(NI)(TM__R8z9bzATizpQoD67YeHNTdg_17)])) & ((NI) 63)));
#line 129 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(129, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");						if (nimAddInt(i, ((NI) 4), &TM__R8z9bzATizpQoD67YeHNTdg_18)) { raiseOverflow(); };						i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_18);}					}
					goto LA27_;
					LA29_: ;
					{						NI TM__R8z9bzATizpQoD67YeHNTdg_19;
#line 131 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(131, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");						result_2 = ((NI) 65533);
#line 132 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(132, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");						if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_19)) { raiseOverflow(); };						i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_19);					}
					LA27_: ;
}				}
				goto LA4_;
				LA25_: ;
				{					NI TM__R8z9bzATizpQoD67YeHNTdg_20;
#line 134 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(134, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");					result_2 = ((NI) 65533);
#line 135 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(135, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");					if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_20)) { raiseOverflow(); };					i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_20);				}
				LA4_: ;

#line 151 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(151, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");				ch = result_2;
#line 151 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				{
#line 153 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(153, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");					if (!(ch <= ((NI) 65535))) goto LA35_;
{
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(154, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");					{						NIM_BOOL T39_;
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						T39_ = (NIM_BOOL)0;
#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						T39_ = (((NI) 55296) <= ch);						if (!(T39_)) goto LA40_;

#line 154 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						T39_ = (ch <= ((NI) 57343));						LA40_: ;
						if (!T39_) goto LA41_;
{
#line 155 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(155, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");						result.data[d] = ((NI16) -3);}					}
					goto LA37_;
					LA41_: ;
					{
#line 157 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
						nimln_(157, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");						result.data[d] = ((NI16) (((NU16) (ch))));					}
					LA37_: ;
}				}
				goto LA33_;
				LA35_: ;
				{
#line 158 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(158, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");					if (!(((NI) 1114111) < ch)) goto LA45_;
{
#line 159 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(159, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");					result.data[d] = ((NI16) -3);}				}
				goto LA33_;
				LA45_: ;
				{					NI TM__R8z9bzATizpQoD67YeHNTdg_21;					NI TM__R8z9bzATizpQoD67YeHNTdg_22;					NI TM__R8z9bzATizpQoD67YeHNTdg_23;					NI TM__R8z9bzATizpQoD67YeHNTdg_24;
#line 161 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(161, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 161 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					if (nimSubInt(ch, ((NI) 65536), &TM__R8z9bzATizpQoD67YeHNTdg_21)) { raiseOverflow(); };					NI ch_2 = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_21);

#line 162 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(162, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 162 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 162 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					if (nimAddInt((NI)((NI64)(ch_2) >> (NU64)(((NI) 10))), ((NI) 55296), &TM__R8z9bzATizpQoD67YeHNTdg_22)) { raiseOverflow(); };					result.data[d] = ((NI16) (((NU16) ((NI)(TM__R8z9bzATizpQoD67YeHNTdg_22)))));
#line 163 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(163, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");					if (nimAddInt(d, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_23)) { raiseOverflow(); };					d = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_23);
#line 164 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(164, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 164 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 164 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					if (nimAddInt((NI)(ch_2 & ((NI) 1023)), ((NI) 56320), &TM__R8z9bzATizpQoD67YeHNTdg_24)) { raiseOverflow(); };					result.data[d] = ((NI16) (((NU16) ((NI)(TM__R8z9bzATizpQoD67YeHNTdg_24)))));				}
				LA33_: ;

#line 151 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(151, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");				if (nimAddInt(d, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_25)) { raiseOverflow(); };				d = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_25);			} LA3: ;
		}
	}

#line 166 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(166, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	result.data[d] = ((NI16) 0);	popFrame();	return result;}

#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {	NCSTRING result;	result = (char*)0;
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
	{
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
		if (!(s.len == ((NI) 0))) goto LA3_;
{
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
		result = "";}	}
	goto LA1_;
	LA3_: ;
	{
#line 92 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
		result = ((char*) ((*s.p).data));	}
	LA1_: ;
	return result;}

#line 173 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A, newWideCString__systemZwidestrs_276)(NimStringV2 s) {	tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A result;	nimfr_("newWideCString", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A));
#line 174 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(174, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 174 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 174 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	result = newWideCString__systemZwidestrs_251(nimToCStringConv(s), s.len);	popFrame();	return result;}

#line 28 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___systemZwidestrs_6)(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A& a) {	nimfr_("=destroy", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 29 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(29, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	{
#line 29 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 29 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
		if (!!((a.data == ((NI16*) NIM_NIL)))) goto LA3_;
{
#line 33 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
		nimln_(33, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 33 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
		dealloc(((void*) (a.data)));
}	}
	LA3_: ;
	popFrame();}

#line 45 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
static N_INLINE(NI, nimCStrLen)(NCSTRING a) {	NI result;	result = (NI)0;
#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
	size_t T1_ = strlen(a);	result = ((NI) (T1_));	return result;}

#line 168 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A, newWideCString__systemZwidestrs_270)(NCSTRING s) {	tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A result;	nimfr_("newWideCString", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");{	nimZeroMem((void*)(&result), sizeof(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A));
#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(169, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	{
#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
		if (!(s == 0)) goto LA3_;
{
#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
		nimZeroMem((void*)(&result), sizeof(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A));		result.bytes = ((NI) 0);		result.data = ((NI16*) NIM_NIL);		goto BeforeRet_;
}	}
	LA3_: ;

#line 171 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(171, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 171 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 171 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	result = newWideCString__systemZwidestrs_251(s, (s ? nimCStrLen(s) : 0));	}BeforeRet_: ;
	popFrame();	return result;}

#line 66 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
N_LIB_PRIVATE N_NIMCALL(NI, ord__systemZwidestrs_44)(NI16 arg) {	NI result;	nimfr_("ord", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	result = (NI)0;
#line 66 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(66, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	result = ((NI) (((NU16) (arg))));	popFrame();	return result;}

#line 65 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
static N_INLINE(void, nimAddCharV1)(NimStringV2& s, NIM_CHAR c) {	NI TM__R8z9bzATizpQoD67YeHNTdg_31;	NI TM__R8z9bzATizpQoD67YeHNTdg_32;
#line 67 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"

#line 67 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
	prepareAdd(s, ((NI) 1));

#line 68 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
	(*s.p).data[s.len] = c;
#line 69 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
	if (nimAddInt(s.len, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_31)) { raiseOverflow(); };
#line 69 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
	(*s.p).data[(NI)(TM__R8z9bzATizpQoD67YeHNTdg_31)] = 0;
#line 70 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
	if (nimAddInt(s.len, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_32)) { raiseOverflow(); };	s.len = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_32);}

#line 176 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZwidestrs_279)(NI16* w, NI estimate, NI replacement) {	NimStringV2 result;	NI TM__R8z9bzATizpQoD67YeHNTdg_26;	nimfr_("$", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	result.len = 0; result.p = NIM_NIL;
#line 177 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(177, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 177 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 177 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 177 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	if (nimAddInt(estimate, (NI)((NI64)(estimate) >> (NU64)(((NI) 2))), &TM__R8z9bzATizpQoD67YeHNTdg_26)) { raiseOverflow(); };	if (((NI)(TM__R8z9bzATizpQoD67YeHNTdg_26)) < ((NI) 0) || ((NI)(TM__R8z9bzATizpQoD67YeHNTdg_26)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__R8z9bzATizpQoD67YeHNTdg_26), ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 177 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	result = rawNewString(((NI) ((NI)(TM__R8z9bzATizpQoD67YeHNTdg_26))));
#line 179 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(179, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	NI i = ((NI) 0);
	{
#line 180 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
		nimln_(180, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");		while (1) {			NI TM__R8z9bzATizpQoD67YeHNTdg_27;
#line 180 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 180 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
			if (!!((w[i] == ((NI16) 0)))) goto LA2;

#line 181 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
			nimln_(181, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 181 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 181 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
			NI T3_ = ord__systemZwidestrs_44(w[i]);			NI ch = T3_;

#line 182 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
			nimln_(182, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");			if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_27)) { raiseOverflow(); };			i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_27);
#line 183 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
			nimln_(183, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");			{				NIM_BOOL T6_;
#line 183 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				T6_ = (NIM_BOOL)0;
#line 183 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				T6_ = (((NI) 55296) <= ch);				if (!(T6_)) goto LA7_;

#line 183 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				T6_ = (ch <= ((NI) 56319));				LA7_: ;
				if (!T6_) goto LA8_;
{
#line 185 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(185, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 185 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 185 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				NI T10_ = ord__systemZwidestrs_44(w[i]);				NI ch2 = T10_;

#line 188 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(188, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");				{					NIM_BOOL T13_;					NI TM__R8z9bzATizpQoD67YeHNTdg_28;					NI TM__R8z9bzATizpQoD67YeHNTdg_29;					NI TM__R8z9bzATizpQoD67YeHNTdg_30;
#line 188 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					T13_ = (NIM_BOOL)0;
#line 188 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					T13_ = (((NI) 56320) <= ch2);					if (!(T13_)) goto LA14_;

#line 188 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					T13_ = (ch2 <= ((NI) 57343));					LA14_: ;
					if (!T13_) goto LA15_;
{
#line 189 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(189, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 189 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 189 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 189 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 189 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 189 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					if (nimAddInt((NI)((NU64)((NI)(ch & ((NI) 1023))) << (NU64)(((NI) 10))), (NI)(ch2 & ((NI) 1023)), &TM__R8z9bzATizpQoD67YeHNTdg_28)) { raiseOverflow(); };					if (nimAddInt((NI)(TM__R8z9bzATizpQoD67YeHNTdg_28), ((NI) 65536), &TM__R8z9bzATizpQoD67YeHNTdg_29)) { raiseOverflow(); };					ch = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_29);
#line 190 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(190, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");					if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_30)) { raiseOverflow(); };					i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_30);}				}
				goto LA11_;
				LA15_: ;
				{
#line 193 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
					nimln_(193, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");					ch = replacement;				}
				LA11_: ;
}			}
			goto LA4_;
			LA8_: ;
			{				NIM_BOOL T19_;
#line 194 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(194, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");				T19_ = (NIM_BOOL)0;
#line 194 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				T19_ = (((NI) 56320) <= ch);				if (!(T19_)) goto LA20_;

#line 194 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				T19_ = (ch <= ((NI) 57343));				LA20_: ;
				if (!T19_) goto LA21_;
{
#line 196 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(196, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");				ch = replacement;}			}
			goto LA4_;
			LA21_: ;
			LA4_: ;

#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
			nimln_(198, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");			{
#line 198 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				if (!(ch < ((NI) 128))) goto LA25_;
{
#line 199 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(199, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 199 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				if ((ch) < ((NI) 0) || (ch) > ((NI) 255)){ raiseRangeErrorI(ch, ((NI) 0), ((NI) 255)); }				nimAddCharV1(result, ((NIM_CHAR) (((NI) (ch)))));}			}
			goto LA23_;
			LA25_: ;
			{
#line 200 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(200, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");				if (!(ch < ((NI) 2048))) goto LA28_;
{
#line 201 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(201, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 201 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 201 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 201 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				if (((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) | ((NI) 192))) < ((NI) 0) || ((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) | ((NI) 192))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) | ((NI) 192)), ((NI) 0), ((NI) 255)); }				nimAddCharV1(result, ((NIM_CHAR) (((NI) ((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) | ((NI) 192)))))));
#line 202 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(202, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 202 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 202 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 202 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				if (((NI)((NI)(ch & ((NI) 63)) | ((NI) 128))) < ((NI) 0) || ((NI)((NI)(ch & ((NI) 63)) | ((NI) 128))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)(ch & ((NI) 63)) | ((NI) 128)), ((NI) 0), ((NI) 255)); }				nimAddCharV1(result, ((NIM_CHAR) (((NI) ((NI)((NI)(ch & ((NI) 63)) | ((NI) 128)))))));}			}
			goto LA23_;
			LA28_: ;
			{
#line 203 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(203, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");				if (!(ch < ((NI) 65536))) goto LA31_;
{
#line 204 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(204, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 204 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 204 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 204 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				if (((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) | ((NI) 224))) < ((NI) 0) || ((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) | ((NI) 224))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) | ((NI) 224)), ((NI) 0), ((NI) 255)); }				nimAddCharV1(result, ((NIM_CHAR) (((NI) ((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) | ((NI) 224)))))));
#line 205 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(205, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 205 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 205 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 205 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 205 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				if (((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128))) < ((NI) 0) || ((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128)), ((NI) 0), ((NI) 255)); }				nimAddCharV1(result, ((NIM_CHAR) (((NI) ((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128)))))));
#line 206 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(206, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 206 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 206 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 206 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				if (((NI)((NI)(ch & ((NI) 63)) | ((NI) 128))) < ((NI) 0) || ((NI)((NI)(ch & ((NI) 63)) | ((NI) 128))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)(ch & ((NI) 63)) | ((NI) 128)), ((NI) 0), ((NI) 255)); }				nimAddCharV1(result, ((NIM_CHAR) (((NI) ((NI)((NI)(ch & ((NI) 63)) | ((NI) 128)))))));}			}
			goto LA23_;
			LA31_: ;
			{
#line 207 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(207, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");				if (!(ch <= ((NI) 1114111))) goto LA34_;
{
#line 208 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(208, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 208 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 208 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 208 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				if (((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 18))) | ((NI) 240))) < ((NI) 0) || ((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 18))) | ((NI) 240))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 18))) | ((NI) 240)), ((NI) 0), ((NI) 255)); }				nimAddCharV1(result, ((NIM_CHAR) (((NI) ((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 18))) | ((NI) 240)))))));
#line 209 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(209, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 209 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 209 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 209 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 209 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				if (((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) & ((NI) 63)) | ((NI) 128))) < ((NI) 0) || ((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) & ((NI) 63)) | ((NI) 128))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) & ((NI) 63)) | ((NI) 128)), ((NI) 0), ((NI) 255)); }				nimAddCharV1(result, ((NIM_CHAR) (((NI) ((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) & ((NI) 63)) | ((NI) 128)))))));
#line 210 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(210, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 210 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 210 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 210 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 210 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				if (((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128))) < ((NI) 0) || ((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128)), ((NI) 0), ((NI) 255)); }				nimAddCharV1(result, ((NIM_CHAR) (((NI) ((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128)))))));
#line 211 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(211, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 211 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 211 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 211 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				if (((NI)((NI)(ch & ((NI) 63)) | ((NI) 128))) < ((NI) 0) || ((NI)((NI)(ch & ((NI) 63)) | ((NI) 128))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)(ch & ((NI) 63)) | ((NI) 128)), ((NI) 0), ((NI) 255)); }				nimAddCharV1(result, ((NIM_CHAR) (((NI) ((NI)((NI)(ch & ((NI) 63)) | ((NI) 128)))))));}			}
			goto LA23_;
			LA34_: ;
			{
#line 214 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(214, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");				nimAddCharV1(result, 239);
#line 215 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(215, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");				nimAddCharV1(result, 191);
#line 216 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
				nimln_(216, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");				nimAddCharV1(result, 189);			}
			LA23_: ;
		} LA2: ;
	}
	popFrame();	return result;}

#line 218 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZwidestrs_343)(NI16* s) {	NimStringV2 result;	nimfr_("$", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	result.len = 0; result.p = NIM_NIL;
#line 219 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(219, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 219 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	result = dollar___systemZwidestrs_279(s, ((NI) 80), ((NI) 65533));	popFrame();	return result;}

#line 37 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqsink___systemZwidestrs_27)(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A& a, tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A b) {	nimfr_("=sink", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 38 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(38, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	a.bytes = b.bytes;
#line 39 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(39, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	a.data = b.data;	popFrame();}

#line 222 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZwidestrs_346)(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A s, NI estimate, NI replacement) {	NimStringV2 result;	nimfr_("$", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	result.len = 0; result.p = NIM_NIL;
#line 223 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(223, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 223 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	result = dollar___systemZwidestrs_279(s.data, estimate, replacement);	popFrame();	return result;}

#line 145 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A, newWideCString__systemZwidestrs_248)(NI size) {	tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A result;	NI TM__R8z9bzATizpQoD67YeHNTdg_33;	NI TM__R8z9bzATizpQoD67YeHNTdg_34;	nimfr_("newWideCString", "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A));
#line 146 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	nimln_(146, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim");
#line 146 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"

#line 146 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	if (nimMulInt(size, ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_33)) { raiseOverflow(); };	if (nimAddInt((NI)(TM__R8z9bzATizpQoD67YeHNTdg_33), ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_34)) { raiseOverflow(); };
#line 146 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\widestrs.nim"
	createWide__systemZwidestrs_30(result, (NI)(TM__R8z9bzATizpQoD67YeHNTdg_34));
	popFrame();	return result;}
