/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)

#line 306 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_184)(NI x) {	NI result;	result = (NI)0;
#line 319 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 319 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"
	result = (NI)(x - ((NI) 1));
#line 321 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 321 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 321 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 32))));
#line 323 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 323 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 323 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 16))));
#line 325 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 325 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 325 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 8))));
#line 326 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 326 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 326 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 4))));
#line 327 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 327 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 327 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 2))));
#line 328 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 328 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 328 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 1))));
#line 329 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 329 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 329 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"

#line 329 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\math.nim"
	result += (NI)(((NI) 1) + (x <= ((NI) 0)));	return result;}
