/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  struct NimStrPayload;
struct NimStringV2;
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
typedef NIM_CHAR tyArray__PbS9a6gkxCuxWEnFq4lOU9aw[24];
typedef NIM_CHAR tyArray__38Z69amCaoywES5tRmClBSw[200];
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2& s, NI newLen);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2& s);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_2330)(NimStringV2& s);
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_171)(NimStringV2& result, NU64 x);
static N_INLINE(void, addIntImpl__stdZprivateZdigitsutils_71)(NimStringV2& result, NU64 x);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
static N_INLINE(void, addChars__stdZprivateZdigitsutils_112)(NimStringV2& result, tyArray__PbS9a6gkxCuxWEnFq4lOU9aw x, NI start, NI n);
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4399)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE NIM_CONST tyArray__38Z69amCaoywES5tRmClBSw digits100__stdZprivateZdigitsutils_2 = {48,
48,
48,
49,
48,
50,
48,
51,
48,
52,
48,
53,
48,
54,
48,
55,
48,
56,
48,
57,
49,
48,
49,
49,
49,
50,
49,
51,
49,
52,
49,
53,
49,
54,
49,
55,
49,
56,
49,
57,
50,
48,
50,
49,
50,
50,
50,
51,
50,
52,
50,
53,
50,
54,
50,
55,
50,
56,
50,
57,
51,
48,
51,
49,
51,
50,
51,
51,
51,
52,
51,
53,
51,
54,
51,
55,
51,
56,
51,
57,
52,
48,
52,
49,
52,
50,
52,
51,
52,
52,
52,
53,
52,
54,
52,
55,
52,
56,
52,
57,
53,
48,
53,
49,
53,
50,
53,
51,
53,
52,
53,
53,
53,
54,
53,
55,
53,
56,
53,
57,
54,
48,
54,
49,
54,
50,
54,
51,
54,
52,
54,
53,
54,
54,
54,
55,
54,
56,
54,
57,
55,
48,
55,
49,
55,
50,
55,
51,
55,
52,
55,
53,
55,
54,
55,
55,
55,
56,
55,
57,
56,
48,
56,
49,
56,
50,
56,
51,
56,
52,
56,
53,
56,
54,
56,
55,
56,
56,
56,
57,
57,
48,
57,
49,
57,
50,
57,
51,
57,
52,
57,
53,
57,
54,
57,
55,
57,
56,
57,
57}
;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;

#line 52 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 46 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 46 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI r = ((NI) ((NU)((NU64)(((NU) (a))) + (NU64)(((NU) (b))))));

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{		NIM_BOOL T3_;
#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ a));		if (T3_) goto LA4_;

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ b));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 48 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA1_;
	LA5_: ;
	{
#line 50 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 168 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2& s) {
#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
	{		NIM_BOOL T3_;
#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
		T3_ = (NIM_BOOL)0;
#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"

#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
		T3_ = !((s.p == ((NimStrPayload*) NIM_NIL)));		if (!(T3_)) goto LA4_;

#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"

#line 169 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
		T3_ = ((NI)((*s.p).cap & ((NI) IL64(4611686018427387904))) == ((NI) IL64(4611686018427387904)));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 170 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"

#line 170 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
		nimPrepareStrMutationImpl__system_2330(s);
}	}
	LA5_: ;
}

#line 64 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI r = ((NI) ((NU)((NU64)(((NU) (a))) - (NU64)(((NU) (b))))));

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{		NIM_BOOL T3_;
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ a));		if (T3_) goto LA4_;

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ (NI)((NU64) ~(b))));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 60 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA1_;
	LA5_: ;
	{
#line 62 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 8 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
#line 10 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"

#line 10 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
	void* T1_ = memcpy(dest, source, ((size_t) (size)));}

#line 2234 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size) {
#line 2235 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"

#line 2235 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
	nimCopyMem(dest, source, size);
}

#line 549 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!(framePtr__system_3905 == ((TFrame*) NIM_NIL))) goto LA3_;
{
#line 551 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = ((NI16) 0);}	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__system_3905).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	(*s).prev = framePtr__system_3905;
#line 557 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = s;
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		callDepthLimitReached__system_4399();
}	}
	LA8_: ;
}

#line 99 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = (*framePtr__system_3905).prev;}

#line 42 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
static N_INLINE(void, addChars__stdZprivateZdigitsutils_112)(NimStringV2& result, tyArray__PbS9a6gkxCuxWEnFq4lOU9aw x, NI start, NI n) {	NI TM__J7BLF9cgvwzEso7aEL9cCOKw_7;	nimfr_("addChars", "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 43 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	nimln_(43, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 43 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	NI old = result.len;

#line 44 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	nimln_(44, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 44 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	if (nimAddInt(old, n, &TM__J7BLF9cgvwzEso7aEL9cCOKw_7)) { raiseOverflow(); };	if (((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_7)) < ((NI) 0) || ((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_7)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_7), ((NI) 0), ((NI) IL64(9223372036854775807))); }	setLengthStrV2(result, ((NI) ((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_7))));
#line 52 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	nimln_(52, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");	if (old < 0 || old >= result.len){ raiseIndexError2(old,result.len-1); }	if ((NU)(start) > (NU)(23)){ raiseIndexError2(start, 23); }	if ((n) < ((NI) 0) || (n) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(n, ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 52 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	copyMem__system_1709(((void*) ((&result.p->data[old]))), ((void*) ((&x[(start)- 0]))), ((NI) (n)));
	popFrame();}

#line 57 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
static N_INLINE(void, addIntImpl__stdZprivateZdigitsutils_71)(NimStringV2& result, NU64 x) {	tyArray__PbS9a6gkxCuxWEnFq4lOU9aw tmp;	NI TM__J7BLF9cgvwzEso7aEL9cCOKw_8;	nimfr_("addIntImpl", "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	nimln_(59, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");	NU64 num = x;

#line 60 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	nimln_(60, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");	NI next = ((NI) 23);
	{
#line 63 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		nimln_(63, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");		while (1) {			NI TM__J7BLF9cgvwzEso7aEL9cCOKw_3;			NI TM__J7BLF9cgvwzEso7aEL9cCOKw_4;
#line 63 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
			if (!((NU64)(100ULL) <= (NU64)(num))) goto LA2;

#line 64 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
			nimln_(64, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");			NU64 originNum = num;

#line 65 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
			nimln_(65, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 65 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
			num = (NU64)((NU64)(num) / (NU64)(100ULL));
#line 66 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
			nimln_(66, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 66 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"

#line 66 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"

#line 66 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
			NU64 index = (NU64)((NU64)((NU64)((NU64)(originNum) - (NU64)((NU64)((NU64)(num) * (NU64)(100ULL))))) << (NU64)(((NI) 1)));
			if ((NU)(next) > (NU)(23)){ raiseIndexError2(next, 23); }
#line 67 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
			nimln_(67, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 67 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
			if ((NU)((NU64)((NU64)(index) + (NU64)(1ULL))) > (NU)(199)){ raiseIndexError2((NU64)((NU64)(index) + (NU64)(1ULL)), 199); }			tmp[(next)- 0] = digits100__stdZprivateZdigitsutils_2[((NU64)((NU64)(index) + (NU64)(1ULL)))- 0];
#line 68 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
			nimln_(68, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");			if (nimSubInt(next, ((NI) 1), &TM__J7BLF9cgvwzEso7aEL9cCOKw_3)) { raiseOverflow(); };			if ((NU)((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_3)) > (NU)(23)){ raiseIndexError2((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_3), 23); }
#line 68 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
			if ((NU)(index) > (NU)(199)){ raiseIndexError2(index, 199); }			tmp[((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_3))- 0] = digits100__stdZprivateZdigitsutils_2[(index)- 0];
#line 69 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
			nimln_(69, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");			if (nimSubInt(next, ((NI) 2), &TM__J7BLF9cgvwzEso7aEL9cCOKw_4)) { raiseOverflow(); };			next = (NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_4);		} LA2: ;
	}

#line 72 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	nimln_(72, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");	{
#line 72 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		if (!((NU64)(num) < (NU64)(10ULL))) goto LA5_;
{		if ((NU)(next) > (NU)(23)){ raiseIndexError2(next, 23); }
#line 73 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		nimln_(73, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 73 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"

#line 73 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		if ((NU64)((NU64)(48ULL) + (NU64)(num)) > (NU64)(((NI) 255))){ raiseRangeErrorNoArgs(); }		tmp[(next)- 0] = ((NIM_CHAR) (((NI) ((NU64)((NU64)(48ULL) + (NU64)(num))))));}	}
	goto LA3_;
	LA5_: ;
	{		NI TM__J7BLF9cgvwzEso7aEL9cCOKw_5;		NI TM__J7BLF9cgvwzEso7aEL9cCOKw_6;
#line 75 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		nimln_(75, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 75 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		NU64 index_2 = (NU64)((NU64)(num) * (NU64)(2ULL));
		if ((NU)(next) > (NU)(23)){ raiseIndexError2(next, 23); }
#line 76 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		nimln_(76, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 76 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		if ((NU)((NU64)((NU64)(index_2) + (NU64)(1ULL))) > (NU)(199)){ raiseIndexError2((NU64)((NU64)(index_2) + (NU64)(1ULL)), 199); }		tmp[(next)- 0] = digits100__stdZprivateZdigitsutils_2[((NU64)((NU64)(index_2) + (NU64)(1ULL)))- 0];
#line 77 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		nimln_(77, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");		if (nimSubInt(next, ((NI) 1), &TM__J7BLF9cgvwzEso7aEL9cCOKw_5)) { raiseOverflow(); };		if ((NU)((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_5)) > (NU)(23)){ raiseIndexError2((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_5), 23); }
#line 77 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		if ((NU)(index_2) > (NU)(199)){ raiseIndexError2(index_2, 199); }		tmp[((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_5))- 0] = digits100__stdZprivateZdigitsutils_2[(index_2)- 0];
#line 78 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		nimln_(78, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");		if (nimSubInt(next, ((NI) 1), &TM__J7BLF9cgvwzEso7aEL9cCOKw_6)) { raiseOverflow(); };		next = (NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_6);	}
	LA3_: ;

#line 79 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	nimln_(79, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 79 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	if (nimSubInt(((NI) 24), next, &TM__J7BLF9cgvwzEso7aEL9cCOKw_8)) { raiseOverflow(); };
#line 79 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	addChars__stdZprivateZdigitsutils_112(result, tmp, next, (NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_8));
	popFrame();}

#line 84 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_171)(NimStringV2& result, NU64 x) {	nimfr_("addInt", "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 87 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	nimln_(87, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 87 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	addIntImpl__stdZprivateZdigitsutils_71(result, x);
	popFrame();}

#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_174)(NimStringV2& result, NI64 x) {	NU64 numX60gensym3_;	nimfr_("addInt", "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");	numX60gensym3_ = (NU64)0;
#line 99 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	nimln_(99, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");	{		NI TM__J7BLF9cgvwzEso7aEL9cCOKw_2;
#line 99 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		if (!(x < IL64(0))) goto LA3_;
{
#line 100 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		nimln_(100, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");		{
#line 100 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
			if (!(x == (IL64(-9223372036854775807) - IL64(1)))) goto LA7_;
{
#line 101 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
			nimln_(101, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");			numX60gensym3_ = ((NU64) (x));}		}
		goto LA5_;
		LA7_: ;
		{
#line 103 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
			nimln_(103, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 103 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
			if (x == (IL64(-9223372036854775807) - IL64(1))){ raiseOverflow(); }			numX60gensym3_ = ((NU64) (-(x)));		}
		LA5_: ;

#line 104 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		nimln_(104, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 104 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		NI baseX60gensym3_ = result.len;

#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		nimln_(105, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 105 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		if (nimAddInt(baseX60gensym3_, ((NI) 1), &TM__J7BLF9cgvwzEso7aEL9cCOKw_2)) { raiseOverflow(); };		if (((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_2)) < ((NI) 0) || ((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_2)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_2), ((NI) 0), ((NI) IL64(9223372036854775807))); }		setLengthStrV2(result, ((NI) ((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_2))));		if (baseX60gensym3_ < 0 || baseX60gensym3_ >= result.len){ raiseIndexError2(baseX60gensym3_,result.len-1); }		nimPrepareStrMutationV2(result);
#line 106 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		nimln_(106, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");		result.p->data[baseX60gensym3_] = 45;}	}
	goto LA1_;
	LA3_: ;
	{
#line 108 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
		nimln_(108, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");		numX60gensym3_ = ((NU64) (x));	}
	LA1_: ;

#line 114 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	nimln_(114, "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim");
#line 114 "C:\\Users\\juama\\NimSources\\Nim\\lib\\std\\private\\digitsutils.nim"
	addInt__stdZprivateZdigitsutils_171(result, numX60gensym3_);
	popFrame();}
