/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include "UEDeps.h"
#include "nimbase.h"
    
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  struct NimStrPayload;
struct NimStringV2;
struct tyObject_Table__VeMlpGOPtuinZ0L3bA8jxw;
struct tySequence__lnvTH5LZ9bUNQULLPbbe6SQ;
struct tySequence__lnvTH5LZ9bUNQULLPbbe6SQ_Content;
struct tySequence__5hxl9cFX6SwCU8Yb1PdQUUQ;
struct tySequence__5hxl9cFX6SwCU8Yb1PdQUUQ_Content;
struct tySequence__9b5NZJUTZkdFa3Svyw0Xg2g;
struct tySequence__9b5NZJUTZkdFa3Svyw0Xg2g_Content;
struct tySequence__9b0VuC6zH0O5CvwhjIJP3pg;
struct tySequence__9b0VuC6zH0O5CvwhjIJP3pg_Content;
struct tyTuple__RHlxqIe8EYzN9bFeUc8qCKg;
struct tyTuple__9cZpXTu2awipKZVG0gXHicA;
typedef TMap<FName COMMA FString>  TY__pruF6pCxGONSAZqb2VhV0w;
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
typedef TArray<FName> TY__NStbuH02lbPjQV4xNcaKRg;
struct tySequence__lnvTH5LZ9bUNQULLPbbe6SQ {
  NI len; tySequence__lnvTH5LZ9bUNQULLPbbe6SQ_Content* p;
};
struct tyObject_Table__VeMlpGOPtuinZ0L3bA8jxw {tySequence__lnvTH5LZ9bUNQULLPbbe6SQ data;
NI counter;
};
struct tySequence__5hxl9cFX6SwCU8Yb1PdQUUQ {
  NI len; tySequence__5hxl9cFX6SwCU8Yb1PdQUUQ_Content* p;
};
struct tySequence__9b5NZJUTZkdFa3Svyw0Xg2g {
  NI len; tySequence__9b5NZJUTZkdFa3Svyw0Xg2g_Content* p;
};
typedef TArray<FString> TY__BxUddP7mEAcT9b0bBOzpnmQ;
struct tySequence__9b0VuC6zH0O5CvwhjIJP3pg {
  NI len; tySequence__9b0VuC6zH0O5CvwhjIJP3pg_Content* p;
};
struct tyTuple__RHlxqIe8EYzN9bFeUc8qCKg {
FName Field0;
FString Field1;
};
typedef TArray<UClass*> TY__7XfhfBMct1uIbxqoXUCR4Q;
typedef TMap<UClass* COMMA UClass*>  TY__B3QM4lVi7lEpnK88TTgy7w;
typedef TArray<UScriptStruct*> TY__lJQ4fMOj3oeahQ9c9aaAuYQQ;
typedef TMap<UScriptStruct* COMMA UScriptStruct*>  TY__RZhnUU8cxgLG4erZM67lkw;
typedef TArray<UEnum*> TY__d3Cxh57lAtanKROTxn5h9bg;
typedef TMap<UEnum* COMMA UEnum*>  TY__J7jAZxrMo80ypk0GqZGsAw;
typedef TArray<UDelegateFunction*> TY__xXZBA3dPvq4miNv0EhRbmQ;
typedef TMap<UDelegateFunction* COMMA UDelegateFunction*>  TY__sMZ8tDdUSocQYQ0jaxIEeQ;
struct tyTuple__9cZpXTu2awipKZVG0gXHicA {
NI Field0;
FName Field1;
FString Field2;
};


#ifndef tySequence__lnvTH5LZ9bUNQULLPbbe6SQ_Content_PP
#define tySequence__lnvTH5LZ9bUNQULLPbbe6SQ_Content_PP
struct tySequence__lnvTH5LZ9bUNQULLPbbe6SQ_Content { NI cap; tyTuple__9cZpXTu2awipKZVG0gXHicA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__5hxl9cFX6SwCU8Yb1PdQUUQ_Content_PP
#define tySequence__5hxl9cFX6SwCU8Yb1PdQUUQ_Content_PP
struct tySequence__5hxl9cFX6SwCU8Yb1PdQUUQ_Content { NI cap; FName data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__9b5NZJUTZkdFa3Svyw0Xg2g_Content_PP
#define tySequence__9b5NZJUTZkdFa3Svyw0Xg2g_Content_PP
struct tySequence__9b5NZJUTZkdFa3Svyw0Xg2g_Content { NI cap; FString data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__9b0VuC6zH0O5CvwhjIJP3pg_Content_PP
#define tySequence__9b0VuC6zH0O5CvwhjIJP3pg_Content_PP
struct tySequence__9b0VuC6zH0O5CvwhjIJP3pg_Content { NI cap; tyTuple__RHlxqIe8EYzN9bFeUc8qCKg data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__9b5NZJUTZkdFa3Svyw0Xg2g_Content_PP
#define tySequence__9b5NZJUTZkdFa3Svyw0Xg2g_Content_PP
struct tySequence__9b5NZJUTZkdFa3Svyw0Xg2g_Content { NI cap; FString data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__5hxl9cFX6SwCU8Yb1PdQUUQ_Content_PP
#define tySequence__5hxl9cFX6SwCU8Yb1PdQUUQ_Content_PP
struct tySequence__5hxl9cFX6SwCU8Yb1PdQUUQ_Content { NI cap; FName data[SEQ_DECL_SIZE];};
#endif

      
#line 20 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\definitions.nim"
#pragma warning(disable: 4101) 

static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4399)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(TY__NStbuH02lbPjQV4xNcaKRg, keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZutilsZueutils_213)(TY__pruF6pCxGONSAZqb2VhV0w map);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(void, appendString)(NimStringV2& dest, NimStringV2 src);
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2& s, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1245)(NimStringV2& s, FName x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1251)(NimStringV2& s, FString x);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(tySequence__5hxl9cFX6SwCU8Yb1PdQUUQ, toSeq__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1703)(TY__NStbuH02lbPjQV4xNcaKRg arr);
N_LIB_PRIVATE N_NIMCALL(tySequence__9b5NZJUTZkdFa3Svyw0Xg2g, toSeq__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1851)(TY__BxUddP7mEAcT9b0bBOzpnmQ arr);
N_LIB_PRIVATE N_NIMCALL(TY__BxUddP7mEAcT9b0bBOzpnmQ, values__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1838)(TY__pruF6pCxGONSAZqb2VhV0w map);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__VeMlpGOPtuinZ0L3bA8jxw, initTable__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_2051)(NI initialSize);
N_LIB_PRIVATE N_NIMCALL(tySequence__9b0VuC6zH0O5CvwhjIJP3pg, zip__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_2169)(FName* s1, NI s1Len_0, FString* s2, NI s2Len_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_2374)(tyObject_Table__VeMlpGOPtuinZ0L3bA8jxw& t, FName key, FString val);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__systemZassertions_66)(NimStringV2 msg);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_2285)(tySequence__9b0VuC6zH0O5CvwhjIJP3pg& dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1993)(tySequence__9b5NZJUTZkdFa3Svyw0Xg2g& dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1780)(tySequence__5hxl9cFX6SwCU8Yb1PdQUUQ& dest);
N_LIB_PRIVATE N_NIMCALL(TY__lJQ4fMOj3oeahQ9c9aaAuYQQ, keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_504)(TY__RZhnUU8cxgLG4erZM67lkw map);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_691)(NimStringV2& s, UScriptStruct* x);
N_LIB_PRIVATE N_NIMCALL(TY__7XfhfBMct1uIbxqoXUCR4Q, keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_480)(TY__B3QM4lVi7lEpnK88TTgy7w map);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_846)(NimStringV2& s, UClass* x);
N_LIB_PRIVATE N_NIMCALL(TY__xXZBA3dPvq4miNv0EhRbmQ, keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_552)(TY__sMZ8tDdUSocQYQ0jaxIEeQ map);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_989)(NimStringV2& s, UDelegateFunction* x);
N_LIB_PRIVATE N_NIMCALL(TY__d3Cxh57lAtanKROTxn5h9bg, keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_528)(TY__J7jAZxrMo80ypk0GqZGsAw map);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_1144)(NimStringV2& s, UEnum* x);
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__jdw0TcROwMB9crjKLlrzgJQ_2 = { 3 | NIM_STRLIT_FLAG, "{:}" };
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_3 = {3, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__jdw0TcROwMB9crjKLlrzgJQ_4 = { 1 | NIM_STRLIT_FLAG, "{" };
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_5 = {1, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_4};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__jdw0TcROwMB9crjKLlrzgJQ_7 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_8 = {2, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_7};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__jdw0TcROwMB9crjKLlrzgJQ_11 = { 2 | NIM_STRLIT_FLAG, ": " };
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_12 = {2, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_11};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__jdw0TcROwMB9crjKLlrzgJQ_14 = { 1 | NIM_STRLIT_FLAG, "}" };
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_15 = {1, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_14};
static const struct {
  NI cap; NIM_CHAR data[131+1];
} TM__jdw0TcROwMB9crjKLlrzgJQ_17 = { 131 | NIM_STRLIT_FLAG, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_18 = {131, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_17};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_19 = {3, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_2};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_20 = {1, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_4};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_22 = {2, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_7};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_23 = {2, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_11};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_25 = {1, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_14};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_26 = {3, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_2};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_27 = {1, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_4};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_29 = {2, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_7};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_30 = {2, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_11};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_32 = {1, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_14};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_33 = {3, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_2};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_34 = {1, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_4};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_36 = {2, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_7};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_37 = {2, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_11};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_39 = {1, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_14};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_40 = {3, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_2};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_41 = {1, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_4};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_43 = {2, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_7};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_44 = {2, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_11};
static const NimStringV2 TM__jdw0TcROwMB9crjKLlrzgJQ_46 = {1, (NimStrPayload*)&TM__jdw0TcROwMB9crjKLlrzgJQ_14};
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;
extern TFrame* framePtr__system_3905;

#line 549 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 550 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!(framePtr__system_3905 == ((TFrame*) NIM_NIL))) goto LA3_;
{
#line 551 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = ((NI16) 0);}	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 554 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__system_3905).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	(*s).prev = framePtr__system_3905;
#line 557 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = s;
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
{
#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"

#line 558 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
		callDepthLimitReached__system_4399();
}	}
	LA8_: ;
}

#line 99 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\excpt.nim"
	framePtr__system_3905 = (*framePtr__system_3905).prev;}

#line 18 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
N_LIB_PRIVATE N_NIMCALL(TY__pruF6pCxGONSAZqb2VhV0w, makeTMap__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZcoreuobjectZuobject_1338)(void) {	TY__pruF6pCxGONSAZqb2VhV0w result;	nimfr_("makeTMap", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 18 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(18, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	result = TMap<FName, FString>();	popFrame();	return result;}

#line 39 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
N_LIB_PRIVATE N_NIMCALL(TY__NStbuH02lbPjQV4xNcaKRg, keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZutilsZueutils_213)(TY__pruF6pCxGONSAZqb2VhV0w map) {	TY__NStbuH02lbPjQV4xNcaKRg result;	nimfr_("keys", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 40 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(40, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 40 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	TY__NStbuH02lbPjQV4xNcaKRg arr;

#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(41, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	map.GetKeys(arr);
	result = arr;	popFrame();	return result;}

#line 64 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 58 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI r = ((NI) ((NU)((NU64)(((NU) (a))) - (NU64)(((NU) (b))))));

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{		NIM_BOOL T3_;
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ a));		if (T3_) goto LA4_;

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 59 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ (NI)((NU64) ~(b))));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 60 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA1_;
	LA5_: ;
	{
#line 62 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 8 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
#line 10 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"

#line 10 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
	void* T1_ = memcpy(dest, source, ((size_t) (size)));}

#line 2234 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size) {
#line 2235 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"

#line 2235 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system.nim"
	nimCopyMem(dest, source, size);
}

#line 52 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 46 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 46 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	NI r = ((NI) ((NU)((NU64)(((NU) (a))) + (NU64)(((NU) (b))))));

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
	{		NIM_BOOL T3_;
#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ a));		if (T3_) goto LA4_;

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"

#line 47 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ b));		LA4_: ;
		if (!T3_) goto LA5_;
{
#line 48 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		(*res) = r;}	}
	goto LA1_;
	LA5_: ;
	{
#line 50 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 94 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
static N_INLINE(void, appendString)(NimStringV2& dest, NimStringV2 src) {
#line 95 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
	{		NI TM__jdw0TcROwMB9crjKLlrzgJQ_9;		NI TM__jdw0TcROwMB9crjKLlrzgJQ_10;
#line 95 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
		if (!(((NI) 0) < src.len)) goto LA3_;
{
#line 97 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"

#line 97 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
		if (nimAddInt(src.len, ((NI) 1), &TM__jdw0TcROwMB9crjKLlrzgJQ_9)) { raiseOverflow(); };		if (((NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_9)) < ((NI) 0) || ((NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_9)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_9), ((NI) 0), ((NI) IL64(9223372036854775807))); }
#line 97 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
		copyMem__system_1709(((void*) ((&(*dest.p).data[dest.len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_9))));

#line 98 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\strs_v2.nim"
		if (nimAddInt(dest.len, src.len, &TM__jdw0TcROwMB9crjKLlrzgJQ_10)) { raiseOverflow(); };		dest.len = (NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_10);}	}
	LA3_: ;
}

#line 65 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1169)(TY__pruF6pCxGONSAZqb2VhV0w map) {	NimStringV2 result;	nimfr_("$", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");{	result.len = 0; result.p = NIM_NIL;
#line 66 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(66, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	{		NI32 T3_;
#line 66 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"

#line 66 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		T3_ = (NI32)0;		T3_ = map.Num();		if (!(T3_ == ((NI32) 0))) goto LA4_;
{
#line 67 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		nimln_(67, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 67 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		result = TM__jdw0TcROwMB9crjKLlrzgJQ_3;		goto BeforeRet_;
}	}
	LA4_: ;

#line 68 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(68, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	result = TM__jdw0TcROwMB9crjKLlrzgJQ_5;	{		FName key;		TY__NStbuH02lbPjQV4xNcaKRg colontmp_;
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		colontmp_ = keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZutilsZueutils_213(map);		{			NI i;			NI colontmp__2;			NI T8_;			NI TM__jdw0TcROwMB9crjKLlrzgJQ_6;			i = (NI)0;			colontmp__2 = (NI)0;
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
			nimln_(38, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
			T8_ = (NI)0;			T8_ = colontmp_.Num();			if (nimSubInt(((NI) (T8_)), ((NI) 1), &TM__jdw0TcROwMB9crjKLlrzgJQ_6)) { raiseOverflow(); };			colontmp__2 = (NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_6);
#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
			nimln_(90, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");			NI res = ((NI) 0);
			{
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
				nimln_(91, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");				while (1) {					NI TM__jdw0TcROwMB9crjKLlrzgJQ_13;
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
					if (!(res <= colontmp__2)) goto LA10;

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
					nimln_(38, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");					i = res;
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 39 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
					nimln_(39, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");					if ((i) < ((NI32) (-2147483647 -1)) || (i) > ((NI32) 2147483647)){ raiseRangeErrorI(i, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)); }					if ((((NI32) (i))) < ((NI) 0) || (((NI32) (i))) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(((NI32) (i)), ((NI) 0), ((NI) IL64(9223372036854775807))); }					key = colontmp_[((NI) (((NI32) (i))))];
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");					{
#line 70 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
						nimln_(70, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 70 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
						if (!(((NI) 1) < result.len)) goto LA13_;
{
#line 70 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
						prepareAdd(result, 2);appendString(result, TM__jdw0TcROwMB9crjKLlrzgJQ_8);}					}
					LA13_: ;

#line 71 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(71, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 71 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					FString val = map[key];

#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1245(result, key);

#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					prepareAdd(result, 2);appendString(result, TM__jdw0TcROwMB9crjKLlrzgJQ_12);
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"

#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1251(result, val);

#line 93 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
					nimln_(93, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");					if (nimAddInt(res, ((NI) 1), &TM__jdw0TcROwMB9crjKLlrzgJQ_13)) { raiseOverflow(); };					res = (NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_13);				} LA10: ;
			}
		}
	}

#line 75 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(75, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	prepareAdd(result, 1);appendString(result, TM__jdw0TcROwMB9crjKLlrzgJQ_15);	}BeforeRet_: ;
	popFrame();	return result;}

#line 19 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
#line 21 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"

#line 21 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
	void* T1_ = memset(a, v, ((size_t) (size)));}

#line 30 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
#line 31 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"

#line 31 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\memory.nim"
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}

#line 43 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
N_LIB_PRIVATE N_NIMCALL(TY__BxUddP7mEAcT9b0bBOzpnmQ, values__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1838)(TY__pruF6pCxGONSAZqb2VhV0w map) {	TY__BxUddP7mEAcT9b0bBOzpnmQ result;	nimfr_("values", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 44 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(44, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 44 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	TY__BxUddP7mEAcT9b0bBOzpnmQ arr;

#line 45 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(45, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	map.GenerateValueArray(arr);
	result = arr;	popFrame();	return result;}

#line 48 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__VeMlpGOPtuinZ0L3bA8jxw, toTable__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1689)(TY__pruF6pCxGONSAZqb2VhV0w map) {	tyObject_Table__VeMlpGOPtuinZ0L3bA8jxw result;	tySequence__5hxl9cFX6SwCU8Yb1PdQUUQ keys;	tySequence__9b5NZJUTZkdFa3Svyw0Xg2g values;	tyObject_Table__VeMlpGOPtuinZ0L3bA8jxw table;	nimfr_("toTable", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Table__VeMlpGOPtuinZ0L3bA8jxw));	keys.len = 0; keys.p = NIM_NIL;	values.len = 0; values.p = NIM_NIL;	nimZeroMem((void*)(&table), sizeof(tyObject_Table__VeMlpGOPtuinZ0L3bA8jxw));
#line 49 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(49, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 49 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"

#line 49 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	TY__NStbuH02lbPjQV4xNcaKRg T1_ = keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZutilsZueutils_213(map);
#line 49 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	keys = toSeq__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1703(T1_);
#line 50 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(50, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 50 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"

#line 50 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	TY__BxUddP7mEAcT9b0bBOzpnmQ T2_ = values__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1838(map);
#line 50 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	values = toSeq__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1851(T2_);
#line 51 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(51, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 51 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	table = initTable__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_2051(((NI) 32));	{		tySequence__9b0VuC6zH0O5CvwhjIJP3pg colontmp_;		tyTuple__RHlxqIe8EYzN9bFeUc8qCKg* pairs;		NI T4_;		colontmp_.len = 0; colontmp_.p = NIM_NIL;		pairs = (tyTuple__RHlxqIe8EYzN9bFeUc8qCKg*)0;
#line 53 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		nimln_(53, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 53 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		colontmp_ = zip__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_2169(((keys).p) ? (keys.p->data) : NIM_NIL, keys.len, ((values).p) ? (values.p->data) : NIM_NIL, values.len);
#line 235 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim"
		nimln_(235, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim");		NI i = ((NI) 0);

#line 236 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim"
		nimln_(236, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim");
#line 236 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim"
		T4_ = colontmp_.len;		NI L = T4_;
		{
#line 237 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim"
			nimln_(237, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim");			while (1) {				FName key;				FString value;				NI TM__jdw0TcROwMB9crjKLlrzgJQ_16;
#line 237 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim"
				if (!(i < L)) goto LA6;

#line 53 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
				nimln_(53, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");				if (i < 0 || i >= colontmp_.len){ raiseIndexError2(i,colontmp_.len-1); }				pairs = (&colontmp_.p->data[i]);
#line 54 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
				nimln_(54, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");				key = (*pairs).Field0;				value = (*pairs).Field1;
#line 53 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
				nimln_(53, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 53 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
				X5BX5Deq___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_2374(table, key, value);

#line 239 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim"
				nimln_(239, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim");				if (nimAddInt(i, ((NI) 1), &TM__jdw0TcROwMB9crjKLlrzgJQ_16)) { raiseOverflow(); };				i = (NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_16);
#line 240 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim"
				nimln_(240, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim");				{					NI T9_;
#line 240 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim"

#line 240 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim"

#line 240 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim"
					T9_ = colontmp_.len;					if (!!((T9_ == L))) goto LA10_;
{
#line 240 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim"

#line 240 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators.nim"
					failedAssertImpl__systemZassertions_66(TM__jdw0TcROwMB9crjKLlrzgJQ_18);
}				}
				LA10_: ;
			} LA6: ;
		}

#line 283 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\collections\\sequtils.nim"
		nimln_(283, "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\collections\\sequtils.nim");
#line 283 "C:\\Users\\juama\\NimSources\\Nim\\lib\\pure\\collections\\sequtils.nim"
		eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_2285(colontmp_);
	}

#line 56 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(56, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	result = table;
#line 57 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
	nimln_(57, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");
#line 57 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
	eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1993(values);

#line 57 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"

#line 57 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
	eqdestroy___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1780(keys);
	popFrame();	return result;}

#line 25 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
N_LIB_PRIVATE N_NIMCALL(NI, len__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforue_1308)(TY__pruF6pCxGONSAZqb2VhV0w arr) {	NI result;	NI32 T1_;	nimfr_("len", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	result = (NI)0;
#line 25 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(25, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 25 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	T1_ = (NI32)0;	T1_ = arr.Num();	result = ((NI) (T1_));	popFrame();	return result;}

#line 39 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
N_LIB_PRIVATE N_NIMCALL(TY__7XfhfBMct1uIbxqoXUCR4Q, keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_480)(TY__B3QM4lVi7lEpnK88TTgy7w map) {	TY__7XfhfBMct1uIbxqoXUCR4Q result;	nimfr_("keys", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 40 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(40, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 40 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	TY__7XfhfBMct1uIbxqoXUCR4Q arr;

#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(41, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	map.GetKeys(arr);
	result = arr;	popFrame();	return result;}

#line 39 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
N_LIB_PRIVATE N_NIMCALL(TY__lJQ4fMOj3oeahQ9c9aaAuYQQ, keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_504)(TY__RZhnUU8cxgLG4erZM67lkw map) {	TY__lJQ4fMOj3oeahQ9c9aaAuYQQ result;	nimfr_("keys", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 40 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(40, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 40 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	TY__lJQ4fMOj3oeahQ9c9aaAuYQQ arr;

#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(41, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	map.GetKeys(arr);
	result = arr;	popFrame();	return result;}

#line 39 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
N_LIB_PRIVATE N_NIMCALL(TY__d3Cxh57lAtanKROTxn5h9bg, keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_528)(TY__J7jAZxrMo80ypk0GqZGsAw map) {	TY__d3Cxh57lAtanKROTxn5h9bg result;	nimfr_("keys", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 40 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(40, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 40 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	TY__d3Cxh57lAtanKROTxn5h9bg arr;

#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(41, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	map.GetKeys(arr);
	result = arr;	popFrame();	return result;}

#line 39 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
N_LIB_PRIVATE N_NIMCALL(TY__xXZBA3dPvq4miNv0EhRbmQ, keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_552)(TY__sMZ8tDdUSocQYQ0jaxIEeQ map) {	TY__xXZBA3dPvq4miNv0EhRbmQ result;	nimfr_("keys", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 40 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(40, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 40 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	TY__xXZBA3dPvq4miNv0EhRbmQ arr;

#line 41 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(41, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	map.GetKeys(arr);
	result = arr;	popFrame();	return result;}

#line 65 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_591)(TY__RZhnUU8cxgLG4erZM67lkw map) {	NimStringV2 result;	nimfr_("$", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");{	result.len = 0; result.p = NIM_NIL;
#line 66 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(66, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	{		NI32 T3_;
#line 66 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"

#line 66 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		T3_ = (NI32)0;		T3_ = map.Num();		if (!(T3_ == ((NI32) 0))) goto LA4_;
{
#line 67 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		nimln_(67, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 67 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		result = TM__jdw0TcROwMB9crjKLlrzgJQ_19;		goto BeforeRet_;
}	}
	LA4_: ;

#line 68 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(68, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	result = TM__jdw0TcROwMB9crjKLlrzgJQ_20;	{		UScriptStruct* key;		TY__lJQ4fMOj3oeahQ9c9aaAuYQQ colontmp_;		key = (UScriptStruct*)0;
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		colontmp_ = keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_504(map);		{			NI i;			NI colontmp__2;			NI T8_;			NI TM__jdw0TcROwMB9crjKLlrzgJQ_21;			i = (NI)0;			colontmp__2 = (NI)0;
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
			nimln_(38, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
			T8_ = (NI)0;			T8_ = colontmp_.Num();			if (nimSubInt(((NI) (T8_)), ((NI) 1), &TM__jdw0TcROwMB9crjKLlrzgJQ_21)) { raiseOverflow(); };			colontmp__2 = (NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_21);
#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
			nimln_(90, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");			NI res = ((NI) 0);
			{
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
				nimln_(91, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");				while (1) {					NI TM__jdw0TcROwMB9crjKLlrzgJQ_24;
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
					if (!(res <= colontmp__2)) goto LA10;

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
					nimln_(38, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");					i = res;
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 39 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
					nimln_(39, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");					if ((i) < ((NI32) (-2147483647 -1)) || (i) > ((NI32) 2147483647)){ raiseRangeErrorI(i, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)); }					if ((((NI32) (i))) < ((NI) 0) || (((NI32) (i))) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(((NI32) (i)), ((NI) 0), ((NI) IL64(9223372036854775807))); }					key = colontmp_[((NI) (((NI32) (i))))];
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");					{
#line 70 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
						nimln_(70, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 70 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
						if (!(((NI) 1) < result.len)) goto LA13_;
{
#line 70 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
						prepareAdd(result, 2);appendString(result, TM__jdw0TcROwMB9crjKLlrzgJQ_22);}					}
					LA13_: ;

#line 71 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(71, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 71 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					UScriptStruct* val = map[key];

#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_691(result, key);

#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					prepareAdd(result, 2);appendString(result, TM__jdw0TcROwMB9crjKLlrzgJQ_23);
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"

#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_691(result, val);

#line 93 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
					nimln_(93, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");					if (nimAddInt(res, ((NI) 1), &TM__jdw0TcROwMB9crjKLlrzgJQ_24)) { raiseOverflow(); };					res = (NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_24);				} LA10: ;
			}
		}
	}

#line 75 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(75, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	prepareAdd(result, 1);appendString(result, TM__jdw0TcROwMB9crjKLlrzgJQ_25);	}BeforeRet_: ;
	popFrame();	return result;}

#line 65 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_746)(TY__B3QM4lVi7lEpnK88TTgy7w map) {	NimStringV2 result;	nimfr_("$", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");{	result.len = 0; result.p = NIM_NIL;
#line 66 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(66, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	{		NI32 T3_;
#line 66 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"

#line 66 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		T3_ = (NI32)0;		T3_ = map.Num();		if (!(T3_ == ((NI32) 0))) goto LA4_;
{
#line 67 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		nimln_(67, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 67 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		result = TM__jdw0TcROwMB9crjKLlrzgJQ_26;		goto BeforeRet_;
}	}
	LA4_: ;

#line 68 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(68, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	result = TM__jdw0TcROwMB9crjKLlrzgJQ_27;	{		UClass* key;		TY__7XfhfBMct1uIbxqoXUCR4Q colontmp_;		key = (UClass*)0;
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		colontmp_ = keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_480(map);		{			NI i;			NI colontmp__2;			NI T8_;			NI TM__jdw0TcROwMB9crjKLlrzgJQ_28;			i = (NI)0;			colontmp__2 = (NI)0;
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
			nimln_(38, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
			T8_ = (NI)0;			T8_ = colontmp_.Num();			if (nimSubInt(((NI) (T8_)), ((NI) 1), &TM__jdw0TcROwMB9crjKLlrzgJQ_28)) { raiseOverflow(); };			colontmp__2 = (NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_28);
#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
			nimln_(90, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");			NI res = ((NI) 0);
			{
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
				nimln_(91, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");				while (1) {					NI TM__jdw0TcROwMB9crjKLlrzgJQ_31;
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
					if (!(res <= colontmp__2)) goto LA10;

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
					nimln_(38, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");					i = res;
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 39 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
					nimln_(39, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");					if ((i) < ((NI32) (-2147483647 -1)) || (i) > ((NI32) 2147483647)){ raiseRangeErrorI(i, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)); }					if ((((NI32) (i))) < ((NI) 0) || (((NI32) (i))) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(((NI32) (i)), ((NI) 0), ((NI) IL64(9223372036854775807))); }					key = colontmp_[((NI) (((NI32) (i))))];
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");					{
#line 70 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
						nimln_(70, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 70 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
						if (!(((NI) 1) < result.len)) goto LA13_;
{
#line 70 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
						prepareAdd(result, 2);appendString(result, TM__jdw0TcROwMB9crjKLlrzgJQ_29);}					}
					LA13_: ;

#line 71 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(71, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 71 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					UClass* val = map[key];

#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_846(result, key);

#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					prepareAdd(result, 2);appendString(result, TM__jdw0TcROwMB9crjKLlrzgJQ_30);
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"

#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_846(result, val);

#line 93 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
					nimln_(93, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");					if (nimAddInt(res, ((NI) 1), &TM__jdw0TcROwMB9crjKLlrzgJQ_31)) { raiseOverflow(); };					res = (NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_31);				} LA10: ;
			}
		}
	}

#line 75 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(75, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	prepareAdd(result, 1);appendString(result, TM__jdw0TcROwMB9crjKLlrzgJQ_32);	}BeforeRet_: ;
	popFrame();	return result;}

#line 65 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_889)(TY__sMZ8tDdUSocQYQ0jaxIEeQ map) {	NimStringV2 result;	nimfr_("$", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");{	result.len = 0; result.p = NIM_NIL;
#line 66 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(66, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	{		NI32 T3_;
#line 66 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"

#line 66 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		T3_ = (NI32)0;		T3_ = map.Num();		if (!(T3_ == ((NI32) 0))) goto LA4_;
{
#line 67 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		nimln_(67, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 67 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		result = TM__jdw0TcROwMB9crjKLlrzgJQ_33;		goto BeforeRet_;
}	}
	LA4_: ;

#line 68 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(68, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	result = TM__jdw0TcROwMB9crjKLlrzgJQ_34;	{		UDelegateFunction* key;		TY__xXZBA3dPvq4miNv0EhRbmQ colontmp_;		key = (UDelegateFunction*)0;
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		colontmp_ = keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_552(map);		{			NI i;			NI colontmp__2;			NI T8_;			NI TM__jdw0TcROwMB9crjKLlrzgJQ_35;			i = (NI)0;			colontmp__2 = (NI)0;
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
			nimln_(38, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
			T8_ = (NI)0;			T8_ = colontmp_.Num();			if (nimSubInt(((NI) (T8_)), ((NI) 1), &TM__jdw0TcROwMB9crjKLlrzgJQ_35)) { raiseOverflow(); };			colontmp__2 = (NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_35);
#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
			nimln_(90, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");			NI res = ((NI) 0);
			{
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
				nimln_(91, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");				while (1) {					NI TM__jdw0TcROwMB9crjKLlrzgJQ_38;
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
					if (!(res <= colontmp__2)) goto LA10;

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
					nimln_(38, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");					i = res;
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 39 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
					nimln_(39, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");					if ((i) < ((NI32) (-2147483647 -1)) || (i) > ((NI32) 2147483647)){ raiseRangeErrorI(i, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)); }					if ((((NI32) (i))) < ((NI) 0) || (((NI32) (i))) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(((NI32) (i)), ((NI) 0), ((NI) IL64(9223372036854775807))); }					key = colontmp_[((NI) (((NI32) (i))))];
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");					{
#line 70 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
						nimln_(70, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 70 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
						if (!(((NI) 1) < result.len)) goto LA13_;
{
#line 70 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
						prepareAdd(result, 2);appendString(result, TM__jdw0TcROwMB9crjKLlrzgJQ_36);}					}
					LA13_: ;

#line 71 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(71, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 71 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					UDelegateFunction* val = map[key];

#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_989(result, key);

#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					prepareAdd(result, 2);appendString(result, TM__jdw0TcROwMB9crjKLlrzgJQ_37);
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"

#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_989(result, val);

#line 93 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
					nimln_(93, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");					if (nimAddInt(res, ((NI) 1), &TM__jdw0TcROwMB9crjKLlrzgJQ_38)) { raiseOverflow(); };					res = (NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_38);				} LA10: ;
			}
		}
	}

#line 75 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(75, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	prepareAdd(result, 1);appendString(result, TM__jdw0TcROwMB9crjKLlrzgJQ_39);	}BeforeRet_: ;
	popFrame();	return result;}

#line 65 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_1044)(TY__J7jAZxrMo80ypk0GqZGsAw map) {	NimStringV2 result;	nimfr_("$", "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");{	result.len = 0; result.p = NIM_NIL;
#line 66 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(66, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	{		NI32 T3_;
#line 66 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"

#line 66 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		T3_ = (NI32)0;		T3_ = map.Num();		if (!(T3_ == ((NI32) 0))) goto LA4_;
{
#line 67 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		nimln_(67, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 67 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		result = TM__jdw0TcROwMB9crjKLlrzgJQ_40;		goto BeforeRet_;
}	}
	LA4_: ;

#line 68 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(68, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	result = TM__jdw0TcROwMB9crjKLlrzgJQ_41;	{		UEnum* key;		TY__d3Cxh57lAtanKROTxn5h9bg colontmp_;		key = (UEnum*)0;
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
		colontmp_ = keys__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_528(map);		{			NI i;			NI colontmp__2;			NI T8_;			NI TM__jdw0TcROwMB9crjKLlrzgJQ_42;			i = (NI)0;			colontmp__2 = (NI)0;
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
			nimln_(38, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");
#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
			T8_ = (NI)0;			T8_ = colontmp_.Num();			if (nimSubInt(((NI) (T8_)), ((NI) 1), &TM__jdw0TcROwMB9crjKLlrzgJQ_42)) { raiseOverflow(); };			colontmp__2 = (NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_42);
#line 90 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
			nimln_(90, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");			NI res = ((NI) 0);
			{
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
				nimln_(91, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");				while (1) {					NI TM__jdw0TcROwMB9crjKLlrzgJQ_45;
#line 91 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
					if (!(res <= colontmp__2)) goto LA10;

#line 38 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
					nimln_(38, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");					i = res;
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 39 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim"
					nimln_(39, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\array.nim");					if ((i) < ((NI32) (-2147483647 -1)) || (i) > ((NI32) 2147483647)){ raiseRangeErrorI(i, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)); }					if ((((NI32) (i))) < ((NI) 0) || (((NI32) (i))) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(((NI32) (i)), ((NI) 0), ((NI) IL64(9223372036854775807))); }					key = colontmp_[((NI) (((NI32) (i))))];
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");					{
#line 70 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
						nimln_(70, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 70 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
						if (!(((NI) 1) < result.len)) goto LA13_;
{
#line 70 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
						prepareAdd(result, 2);appendString(result, TM__jdw0TcROwMB9crjKLlrzgJQ_43);}					}
					LA13_: ;

#line 71 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(71, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 71 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					UEnum* val = map[key];

#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					nimln_(69, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_1144(result, key);

#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					prepareAdd(result, 2);appendString(result, TM__jdw0TcROwMB9crjKLlrzgJQ_44);
#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"

#line 69 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
					addQuoted__OOZ80luginsZ78im70or8569ZsrcZnimforueZunrealZnimforueZnimforuebindings_1144(result, val);

#line 93 "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim"
					nimln_(93, "C:\\Users\\juama\\NimSources\\Nim\\lib\\system\\iterators_1.nim");					if (nimAddInt(res, ((NI) 1), &TM__jdw0TcROwMB9crjKLlrzgJQ_45)) { raiseOverflow(); };					res = (NI)(TM__jdw0TcROwMB9crjKLlrzgJQ_45);				} LA10: ;
			}
		}
	}

#line 75 "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim"
	nimln_(75, "C:\\Users\\juama\\Projects\\youtube\\NimTemplate\\Plugins\\NimForUE\\src\\nimforue\\unreal\\Core\\Containers\\map.nim");	prepareAdd(result, 1);appendString(result, TM__jdw0TcROwMB9crjKLlrzgJQ_46);	}BeforeRet_: ;
	popFrame();	return result;}
